### ISSUE TITLE
Use system properties on the HttpClient that's used in J4pClientBuilder

### ISSUE THREAD

**Issue by christian-posta** [rhuss/jolokia#169]
At the moment, i can't find a good way to tell the jolokia client to use an http/https proxy. Using the http_proxy env variables don't work; maybe we can enhance the J4pClientBuilder to call HttpClient.custom().useSystemProperties() as part of it's call so we can set system props to configure the http proxy

related: https://github.com/fabric8io/fabric8/issues/2972

**Comment by jcordes73** [comment]
@christian-posta Is it now working for you?

**Comment by rhuss** [comment]
What's the status of this one ? It should work now in the latest Jolokia release, going to close this for now.

Please feel free to reopen if there is still any issue with that.
