### ISSUE TITLE
maxCollectionSize not used?

### ISSUE THREAD

**Issue by michaelmeire** [rhuss/jolokia#176]
We try to use the maxCollectionSize parameter to limit the number of entries at a particular level in the JMX tree, but this does not seem to be picked up?

For example the request we try, is
http://...../api/jolokia/list?maxCollectionSize=2

When doing this request, we still get a lot more elements in a particular collection in the json response.

For your information, we are using version 1.2.1 of jolokia.
To be exact, we are accessing the jolokia version packed with activemq 5.10

**Comment by rhuss** [comment]
With `LIST` you only get meta data about MBeans. Since you are talking about message I suspect that the returned value is part of a `READ` or `EXEC` for which `maxCollectionSize` should work. (Except of course is for each message a MBean would be registered, which is probably (and hopefully) not the case). 

Could you send me the the Jolokia URL how you get the messages ?

**Comment by michaelmeire** [comment]
Actually we are using the feature of Hawtio to make a remote connection to a Jolokia agent that is by default running in ActiveMQ, so we are not composing the URL ourselves. Using firebug, we can see that the following url is executed when making the connection from a hawtio deployed in a local tomcat

http://localhost:58080/hawtio/proxy/http://<domain>:8161/api/jolokia/?maxDepth=7&maxCollectionSize=20&ignoreErrors=true&canonicalNaming=false

with of course <domain> replaced by the machine where activemq is running.

In this URL, the part upto "proxy" is hawtio-specific, so I guess the actual jolokia url that is executed, is 
http://<domain>:8161/api/jolokia/?maxDepth=7&maxCollectionSize=20&ignoreErrors=true&canonicalNaming=false

In this URL, i don't see a list/read/exec?

**Comment by michaelmeire** [comment]
@rhuss, your reply was very helpful, thanks. Knowing that the LIST only returns metadata about MBeans, made us realize that we were facing the problem of having a lot of topics on our ActiveMQ. In that case, even the list returns a lot of mbeans, since there is an mbean per topic.

Even though our specific problem was not a jolokia issue, I guess our post could remain useful, since it explained some stuff that could be useful for others as well.

**Comment by rhuss** [comment]
Yes, of course. If you don't mind, I'll close the issue nevertheless (it can still be found when searched for) in order to clean up my issue list.
