### ISSUE TITLE
Reference manual misleading for response with path.

### ISSUE THREAD

**Issue by rhuss** [rhuss/jolokia#190]
In section 6.1.4 "Pathes" the example is misleading as it seems that only a single value is returned (but its only the "value" part of the response.

See also this dicussion in the [forum](http://jolokia.963608.n3.nabble.com/Inner-paths-always-generating-JSON-tp4024322.html)

**Comment by arnabbiswas1** [comment]
Although, the section 6.1.4 of [documentation] (https://jolokia.org/reference/html/protocol.html) doesn't explicitly mention that the response returned is always a json, other sections (6.1.3 & 6.2.1.3) talks about the format of a complete response as well as about the "value" entry. IMHO, the example responses should be changed to include entries other than "value" in the section 6.1.4. That will provide enough clarification to the reader. For example, response against the URL ```http://localhost:8080/jolokia/read/java.lang:type=Memory/HeapMemoryUsage``` can be changed to: 
```
{
   "value":{
             "init":134217728,
             "max":532742144,
             "committed":133365760,
             "used":19046472
           },
   "status":200,
   "timestamp":....,
   "request":{
               "mbean":"java.lang:type=Memory",
               "type":"read",
               "attribute":"HeapMemoryUsage"
             }
 }
```
And response against the URL ```http://localhost:8080/jolokia/read/java.lang:type=Memory/HeapMemoryUsage/used``` can be changed to: 
```
  {
      "value": 19046472,
      "status": 200,
      "timestamp": ....,
      "request": {
                    "mbean": "java.lang:type=Memory",
                    "path": "used",
                    "attribute": "HeapMemoryUsage",
                    "type": "read"
                }
  }
```

**Comment by arnabbiswas1** [comment]
As per the section 6.1.2 :

```All requests have a common mandatory attribute, type, which specifies the kind of JMX operation to perform. The other attributes are either operation specific as described in Section 6.2, “Jolokia operations” or are processing parameters which influence the overall behaviour and can be mixed in to any request. See Section 6.3, “Processing parameters” for details.``` 

The first line makes an impression that "type" is the ONLY mandatory entry. That is not true. A POST request without "mbean" entry results in an IllegalArgumentException.

**Comment by rhuss** [comment]
Thanks ! I updated the site accordingly to your suggestion. Feel free to reopen the ticker, or even better, send in a pull request if something is still not so clear.
