### ISSUE TITLE
#{...} is not resolved when using Jolokia's Spring configuration

### ISSUE THREAD

**Issue by rhuss** [rhuss/jolokia#192]
Although `${...}` substitution works fine when using `<jolokia:config>` in a Spring configuration, the extended EL with `#{...}` does not.

In addition to fix this, there should be a documentation how the Jolokia agent can be used with the Jolokia specific Spring configuration but with plain beans only.

**Comment by LionelCons** [comment]
Roland, let me know if I can help you with this one...

**Comment by rhuss** [comment]
sorry for the delay, I'm quite busy until May (changing jobs). If you want, you can dive into it. The starting point is [here](https://github.com/rhuss/jolokia/blob/master/agent/jvm-spring/src/main/java/org/jolokia/jvmagent/spring/config/JolokiaNamespaceHandler.java).

**Comment by rhuss** [comment]
As a workaround you can use the following construct to setup Jolokia without using the joloka spring config syntax:

````xml
  <bean name="server" id="jolokia" class="org.jolokia.jvmagent.spring.SpringJolokiaAgent">
    <property name="config">
      <bean class="org.jolokia.jvmagent.spring.SpringJolokiaConfigHolder">
        <property name="config">
          <util:map>
            <entry key="autoStart" value="true"/>
            <entry key="host" value="127.0.0.1"/>
            <entry key="port" value="#{configuration['jmx.jolokiaPort']}"/>
            <entry key="agentContext" value="/jolokia"/>
          </util:map>
        </property>
      </bean>
    </property>
  </bean>
````

**Comment by rhuss** [comment]
I will add this to the documentation.

**Comment by cmoulliard** [comment]
I think that the PropertyPlaceHolder should be added after the lookupConfig - https://github.com/cmoulliard/jolokia/blob/master/agent/jvm-spring/src/main/java/org/jolokia/jvmagent/spring/SpringJolokiaAgent.java#L59

Question : Do we have to exclude in the code the situation where a spring xml file will contain the SpringJolokiaConfigHolder AND also a <context:property-placeholder location="classpath:foo.properties" /> ?

**Comment by rhuss** [comment]
Both are orthogonal and note really related. The `SpringJolokiaConfigHolder` is only a container for map and used as backing bean for the jolokia namespace configuration (therefore this extra indirection which would not be necessary otherwise). The `lookupConfig` is used for having the possibility to separate configuration and installation of the agent. I.e. one could have a library with an unconfigured agent in the spring context and the only add the configuration in another context file (don't know whether this is really often used).

The problem here is that the Spring EL (`#{ ...}`) is  not resolved before the value is injected into the bean when the jolokia namespace is used. Fix shouldn't be hard as soon as I dived into the Spring rabbit hole (which always takes a bit ;-). `${...}` expressions are resolved earlier and are properly injected, though. See also the discussion [here](http://jolokia.963608.n3.nabble.com/Problems-using-Jolokia-amp-Spring-amp-properties-td4024327.html).
