### ISSUE TITLE
Using discoveryAgentUrl will cause all discovered agents to be non secured

### ISSUE THREAD

**Issue by davsclaus** [rhuss/jolokia#193]
I am trying to setup Apache ActiveMQ so it has discovery easily out of the box if people enable it.

As the url is blank by default, I am configuring it in a web.xml file as shown
```
    <servlet>
        <servlet-name>jolokia-agent</servlet-name>
        <servlet-class>org.jolokia.http.AgentServlet</servlet-class>
        <load-on-startup>1</load-on-startup>     
        <init-param>
          <param-name>discoveryEnabled</param-name>
          <param-value>true</param-value>
        </init-param>
        <init-param>
          <param-name>discoveryAgentUrl</param-name>
          <param-value>http://${host}:8161/api/jolokia</param-value>
        </init-param>
        <init-param>
          <param-name>agentDescription</param-name>
          <param-value>Apache ActiveMQ</param-value>
        </init-param>
    </servlet>
```

This ensures I can configure the correct path. 

1)
Now I disable the discoveryAgentUrl init parameter and let jolokia return a default value, to show that the agent is secured.

As the default discovery renders the wrong path, as that becomes /api and not /api/jolokia. See the screenshot below from a web browser with the json returned

![screen shot 2015-04-25 at 8 28 19 am](https://cloud.githubusercontent.com/assets/477100/7331892/a0212ef6-eb24-11e4-859a-bac30a805561.png)

Notice that the json has `secured: true`. 

2)
Now if I enable the discoveryAgentUrl init-parameter and do this again, the json returned is as shown below. As you can see the `secured: true` is gone

![screen shot 2015-04-25 at 8 31 33 am](https://cloud.githubusercontent.com/assets/477100/7331901/067fcd38-eb25-11e4-9453-cf78c9bf2ecf.png)

**Comment by davsclaus** [comment]
So maybe we need a new init-parameter I can use to configure it as secured

```
  <init-param>
          <param-name>discoveryAgentSecured</param-name>
          <param-value>true</param-value>
        </init-param>
```

**Comment by rhuss** [comment]
You are right, this is not consitent. Infact, when an URL is tried to be autodetected then the agentUrl is lazily extracted from the first request that comes in. This also can autodetect the security mode (`HttpRequest.getAuthType()`). 

However, when an URL is provided, no autodetection is tried, even not for the security mode (which is this case sticks undefined). It would be better to allow a config parameter as you suggest and to do autodetection if this parameter is not given (even when the URL is provided). 

I'll will implement that for 1.2.4

**Comment by rhuss** [comment]
I fixed this in so far so that "secure" is always extracted from the first HttpRequest, regardless whether the url is set or autodetected. Hopefully this is good enough so that we can avoid an extra configuration option (we already have quite a moutful of them).
