### ISSUE TITLE
Discovery with ${host} placeholder may use wrong hostname / ip

### ISSUE THREAD

**Issue by davsclaus** [rhuss/jolokia#195]
I can verify that #193 now works with 1.3.0. 

But I noticed that the ${host} placeholder is now my RH VPN IP.
And therefore when I tried to connect to the agent, then it "hangs" as that wont resolve / work.

If I use localhost or 192.168.0.3 or 127.0.0.1 etc then it works.

![host-my-vpn-ip](https://cloud.githubusercontent.com/assets/477100/7519956/ace0ac0c-f4e3-11e4-8b18-0fdd57dd0f92.png)

I am not sure if this is a odd case I have or if the code in jolokia can select eth0 or what network interface that is more appropriate?

**Comment by davsclaus** [comment]
Btw this is the new jolokia 1.3.0 version that is being shipped out of the box in ActiveMQ 5.12 release.

**Comment by rhuss** [comment]
If `${host}` is given, Jolokia tries to autodect the local interface. The algorithm for that is [here](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/util/NetworkUtil.java#L51). It's a bit involved but at the end it picks the first interfaces which is up, supports multitcast, is not an IPv6 adress and is not the loopback interface. The order of the interfaces checked are from `NetworkInterface.getNetworkInterfaces()`. 

What you can do to be more specific is to do an external detection in the startup script, set an environment variable or system property and then use `${env:MY_DETECTED_HOST}` or `${prop:myDetectedProperty}`.

But of course, if you have a better algorithm for selecting the proper interface you are welcome ! (I could filter out tun interface or so or use them only as a last resort ...)

**Comment by davsclaus** [comment]
Thanks for the detailed answer.

The idea with the ENV variable is really good. The ActiveMQ start scripts could benefit from setting such a variable.
