### ISSUE TITLE
Unable to serialize empty TabularData

### ISSUE THREAD

**Issue by sakno** [rhuss/jolokia#200]
Jolokia can't serialize `TabularDataSupport` with empty set of rows. In this case `value` field in the HTTP response contains `null` value:
```json
{"timestamp":1433455091,"status":200,"request":{"mbean":"helloworld:type=SimpleMBean","attribute":"simpleAttribute","type":"read"},"value":null}
```
I found the reason. Look at this line of code:
[TabularDataExtractor.java L200](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/converter/json/TabularDataExtractor.java#L200)

When `TabularData` is empty the loop never iterates and `found` local variable will set to `false`. So `AttributeFilteredException` will cause to unwind call stack and catched in `ObjectToJsonConverter.extractObjectWithContext` method.
```java
try {
            jsonResult = extractObject(pValue, pExtraArgs, pJsonify);
        } catch (ValueFaultHandler.AttributeFilteredException exp) {
            jsonResult = null;
        } finally {
            clearContext();
        }
``` 
Here, `jsonResult` always set to `null` if `AttributeFilteredException` exception occurred.

**Comment by nevenr** [comment]
Hi,

I assumed that empty TabularData should respond to empty JSON object.
Fix is https://github.com/nevenr/jolokia/commit/73afe3498d9945aa8c5e0aec28058714e85b615f.
This commit will be included in https://github.com/rhuss/jolokia/pull/220.

Regards,
N.

**Comment by rhuss** [comment]
Fixed in master
