### ISSUE TITLE
Images missing in jolokia-reference.pdf bundled with jolokia-1.3.1-bin

### ISSUE THREAD

**Issue by arnabbiswas1** [rhuss/jolokia#208]
jolokia-reference.pdf which is shipped with jolokia-1.3.1-bin.tar.gz does not have images referred : 
1. Figure 2.1. Jolokia architecture
2. Figure 2.2. Jolokia as JMX Proxy 
3. Figure 8.1. Horizon Chart for Heap-Memory Usage
4. Figure 9.1. A JsonMBean in jconsole

This is true for the [pdf document] (https://jolokia.org/reference/pdf/jolokia-reference.pdf) referred in the [jolokia portal](https://jolokia.org/documentation.html).

**Comment by rhuss** [comment]
Thanks, I will have a look at it ;-)
