### ISSUE TITLE
Add http header "Content-Type: application/json" to the JSON responses

### ISSUE THREAD

**Issue by lkrzyzanek** [rhuss/jolokia#209]
The correct content type header `Content-Type: application/json` is missing in the response.

**Comment by rhuss** [comment]
You can set the mime type with the query parameter `mimeType=application/json` or as an init parameter of the agent. See also https://jolokia.org/reference/html/protocol.html#processing-parameters for more information. 

That the default mime type is `text/plain` has historical reasons (and there was a good reason at that time which I don't remember by heart right now). Changing defaults is something quite dangerous /wr to backwards compatibility, so without a very, very good reason I won't do that.

**Comment by lkrzyzanek** [comment]
I see. I added

		<init-param>
			<param-name>mimeType</param-name>
			<param-value>application/json</param-value>
		</init-param>

to the servlet in `web.xml` and now it returns correct content type as expected.

Thanks!

**Comment by rhuss** [comment]
Good to know that it works for you ;-)

**Comment by wsapiens** [comment]
I also encountered this issue on jolokia + spring-boot and fixed it by adding below property to **application.properties** file, after reading this post.

`jolokia.config.mimeType=application/json`

now I  see application/json on Content-Type header

`$ curl -v  http://127.0.0.1:8081/management/jolokia/read/java.lang:type=Memory/HeapMemoryUsage
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET /management/jolokia/read/java.lang:type=Memory/HeapMemoryUsage HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:8081
> Accept: */*
> 
< HTTP/1.1 200 
< Cache-Control: no-cache
< Pragma: no-cache
< Date: Wed, 26 Oct 2016 22:02:58 GMT
< Expires: Wed, 26 Oct 2016 21:02:58 GMT
< Content-Type: application/json;charset=utf-8
< Content-Length: 209
< 
* Connection #0 to host 127.0.0.1 left intact
{"request":{"mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","type":"read"},"value":{"init":268435456,"committed":1062207488,"max":3817865216,"used":147393912},"timestamp":1477519378,"status":200}`

**Comment by donatelloOo** [comment]
@wsapiens it doesn't worked for me (using spring-boot 2.3.4.RELEASE).

Using spring-boot, the way to configure Jolokia mimeType must be:

```properties
management.endpoint.jolokia.config.mimeType = application/json
```

As defined in the [spring-boot documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-customizing-jolokia).
