### ISSUE TITLE
Issue with zabbix, hawtio : org.jolokia.client.exception.J4pRemoteException: Forbidden

### ISSUE THREAD

**Issue by arnabbiswas1** [rhuss/jolokia#211]
Hi Roland,

In our project, we use Zabbix for monitoring. On the server to be monitired, hawtio is configured. Between hawtio and zabbix, the following version of the open source zabbix-java-gateway is sitting (This zabbix-java-gateway uses Jolokia Java Client.) :

https://bitbucket.org/ryanrupp/zabbix-java-gateway/wiki/Home

hawtio (jolokia) <--> zabbix-java-gateway <-> zabbix.

On the hawtio (webapp in tomcat) side, authentication is enabled using the flag  "hawtio.authenticationEnabled=true" in CATALINA_OPTS. The problem I see is zabbix-java-gateway is posting the following request to hawtio (zabbix-java-gateway provides username and password information to jolokia client) :

>POST /hawtio/jolokia/ HTTP/1.1
>Content-Length: 110
>Content-Type: text/plain; charset=UTF-8
>Host: 10.104.245.67:80
>Connection: Keep-Alive
>User-Agent: Jolokia JMX-Client (using Apache-HttpClient/4.2.1)
>Expect: 100-continue

And it receives 403 Forbidden. Zabbix does not receive the JMX data because of that.

>HTTP/1.1 403 Forbidden
>Server: nginx
>Date: Sun, 16 Aug 2015 07:25:00 GMT
>Content-Type: text/html; charset=utf-8
>Content-Length: 445
>Connection: keep-alive
>Keep-Alive: timeout=300
>ETag: "55c2e451-1bd"

As I understand, instead of 403 if hawtio returns 401 Unauthorized, jolokia client will send a POST request with authorization information (This is happening for another server where we are using jolokia directly instead of hawtio).

Following this thread in [hawtio] (https://github.com/hawtio/hawtio/issues/1155), I have now set the property "hawtio.noCredentials401=true" in CATALINA_OPTS. Still, hawtio is returning 403 to zabbix_java_gateway's post request. However, with this property, I am getting 401 Unautorized with curl :

curl -v -d "@hawtio_json" http://<hawtio_server>:80/hawtio/jolokia

> POST /hawtio/jolokia HTTP/1.1
> User-Agent: curl/7.37.1
> Host: xx.xx.xx.xx
> Accept: */*
> Content-Length: 112
> Content-Type: application/x-www-form-urlencoded
 

> HTTP/1.1 401 Unauthorized
> Server nginx is not blacklisted
> Server: nginx
> Date: Sun, 16 Aug 2015 06:41:29 GMT
> Content-Length: 0
> Connection: keep-alive
> Keep-Alive: timeout=300
> X-Frame-Options: SAMEORIGIN
> Access-Control-Allow-Origin: *
> WWW-Authenticate: Basic realm="*"

Without hawtio.noCredentials401=true, the response for the request through curl was "403 Forbidden". 

I found another old jolokia [issue] (https://github.com/rhuss/jolokia/issues/141) which is already fixed. There is a possibilty that zabbix_java_gateway is using an loder version of Java Client (1.0.5?). Could that be the problem?

Any suggestion will be highly appreciated.

Thanks,
Arnab

**Comment by arnabbiswas1** [comment]
Well. I wrote last few lines in hurry. :-)

[Changes] (https://github.com/rhuss/jolokia/commit/e159a914aa6759ff01fb9ed70d8174a2ad2399ec) indicate that with the latest client jar preemptive authentication is possible :

>J4pClient j4p = J4pClient.url("http://localhost:8080/jolokia")
>                         .user("roland")
>                         .password("s!cr!t")
>                         .authenticator(new BasicAuthenticator().preemptive())
>                         .connectionTimeout(3000)
>                         .build();

However, the client jar used by zabbix java agent is older (1.0.5).

However, any suggestion will be appreciated.

**Comment by rhuss** [comment]
Sorry for the late response ...

> HTTP/1.1 403 Forbidden
> Server: nginx
> Date: Sun, 16 Aug 2015 07:25:00 GMT

Could it be that there is a reverse proxy sitting between Zabbix and Jolokia which prevents connecting ? The header indicates that an Nginx is involved here. 

Also, how is the agent installed (with hawt.io) at your server ?

**Comment by arnabbiswas1** [comment]
Even when I avoid the NGINX and try to connect zabbix java gateway directly to the port where the server is listening, I get the same 403 Forbidden. Here is the exchange sequence:

POST /hawtio/jolokia/ HTTP/1.1
Content-Length: 116
Content-Type: text/plain; charset=UTF-8
Host: 10.104.245.67:9080
Connection: Keep-Alive
User-Agent: Jolokia JMX-Client (using Apache-HttpClient/4.2.1)
Expect: 100-continue

HTTP/1.1 100 Continue
[{"mbean":"Catalina:name=\"http-nio-0.0.0.0-9080\",type=ThreadPool","attribute":"currentThreadCount","type":"READ"}]

HTTP/1.1 403 Forbidden
Server: Apache-Coyote/1.1
Content-Length: 0
Date: Thu, 03 Sep 2015 14:43:52 GMT
Connection: close 

The hawtio log shows the following : 

2015-09-03 17:46:54,423 | DEBUG | Authentication enabled, denying request for jolokia | io.hawt.web.SessionExpiryFilter | http-nio-0.0.0.0-9080-exec-10
2015-09-03 17:47:55,067 | DEBUG | Authentication enabled, denying request for jolokia | io.hawt.web.SessionExpiryFilter | http-nio-0.0.0.0-9080-exec-4

Please note that in the initial post there is Authorization header.

**Comment by arnabbiswas1** [comment]
Few days back I did another experiment (NGINX was there in between zabbix java gateway and hawtio at that time). I have built zabbix java gateway with the latest Jolokia client. Also I have made sure that Zabbix Java Gateway sends pre-emptive authentication. 

>J4pClientBuilder builder = J4pClient.url(jolokiaUrl)
>                    .socketTimeout(SOCKET_TIMEOUT)
>                    .connectionTimeout(CONNECTION_TIMEOUT)
>                    .expectContinue(false);
>if (null != username) {
>                builder.user(username).password(password).authenticator(new >BasicAuthenticator().preemptive());
 >}

>POST /hawtio/jolokia/ HTTP/1.1
>Content-Length: 73
>Content-Type: text/plain; charset=UTF-8
>Host: 10.104.245.67:80
>Connection: Keep-Alive
>User-Agent: Jolokia JMX-Client (using Apache-HttpClient/4.3.3)
>Expect: 100-continue
>Accept-Encoding: gzip,deflate
>Authorization: Basic YWRtaW46MEt5NHlMQTBIVWlpVnowMw==

But, still 403 Forbidden is returned by hawtio:

>HTTP/1.1 403 Forbidden
>Server: nginx
>Date: Sat, 22 Aug 2015 18:04:21 GMT
>Content-Type: text/html; charset=utf-8
>Content-Length: 445
>Connection: keep-alive
>Keep-Alive: timeout=300
>ETag: "55c2e451-1bd"

The log shows the following: 
>2015-08-22 21:17:31,731 | DEBUG | Checked for Apache Tomcat in JMX for true -> {} | io.hawt.web.tomcat.TomcatAuthenticationContainerDiscovery | localhost-startStop-1
>2015-08-22 21:17:31,732 | INFO  | Discovered container Apache Tomcat to use with hawtio authentication filter | io.hawt.web.AuthenticationFilter | localhost-startStop-1
>2015-08-22 21:17:31,732 | INFO  | Starting hawtio authentication filter, JAAS realm: "*" authorized role(s): "jmxadmin" role principal classes: "io.hawt.web.tomcat.TomcatPrincipal" | io.hawt.web.AuthenticationFilter | localhost-startStop-1
>2015-08-22 21:17:32,046 | DEBUG | Authentication enabled, denying request for jolokia | io.hawt.web.SessionExpiryFilter | http-nio-0.0.0.0-9080-exec-3
>2015-08-22 21:17:40,448 | DEBUG | Authentication enabled, denying request for jolokia | io.hawt.web.SessionExpiryFilter | http-nio-0.0.0.0-9080-exec-15

On checking the source code for "io.hawt.web.SessionExpiryFilter", I found that this log message will be printed (i.e. 403 forbidden will be returned) when Authorization header is not there, but the tcpdump shows that the POST request has the Authorization header. 

Not sure what is the problem. I have posted it to hawtio as well.

**Comment by arnabbiswas1** [comment]
It was an issue (See [here](https://github.com/hawtio/hawtio/commit/633b82ce23473eddb532670f07e072237be94ef7)) on hawtio and it got resolved in 1.4.52. We are using 1.4.48 in our product and hence encountering the problem. 

So, now with 1.4.52, if the initial POST request contains BASIC Authorization, hawtio is responding back with 200 OK. :-)

@rhuss, Please close it on the Jolokia side. I am seeing another issue on hawtio, which I will report there. Thanks for your support!
