### ISSUE TITLE
JBoss AS 7 / JBoss EAP 6 + Jolokia

### ISSUE THREAD

**Issue by nevenr** [rhuss/jolokia#236]
JBoss used in standalone mode and  Jolokia is configured as java agent.
Sometimes /read/jboss.as:deployment=\*  JMX bean not found.
It is needed to restart jboss with jvm jolokia agent several times until, eventually, mbeans are available.
When agent is dynamically detached and attached again, it recovers, mbeans are available.

**Comment by arimus** [comment]
Did you ever find a resolution to this? The ticket is closed, bit there are no comments on how this was resolved or if you managed to get the issue to go away on your own. Not sure it's the exact same issue, but I can see everything except the jboss.as mbean tree.

**Comment by patrikbeno** [comment]
Resolution / Workaround:

Do not try to start jolokia as agent. Start JBoss AS and then use Jolokia's attach capabilities (attach to existing process). This works as expected. 

(Original agent configuration with bootstrap classpath hacking is broken, and probably unsupported.)
