### ISSUE TITLE
Missing a java.util.logging LogHandler

### ISSUE THREAD

**Issue by fbacchella** [rhuss/jolokia#278]
It could be as simple as :

    import java.util.logging.Level;
    import java.util.logging.Logger;

    public final static class JrdsLogHandler implements LogHandler {

        private static final Logger julilogger = Logger.getLogger(SomeClass.class.getCanonicalName());
        @Override
        public void debug(String message) {
            julilogger.fine(message);;
        }

        @Override
        public void info(String message) {
            julilogger.info(message);
        }

        @Override
        public void error(String message, Throwable t) {
            julilogger.log(Level.WARNING, message, t);
        }

    };

**Comment by rhuss** [comment]
Thanks ;-) Will add sth like this to the next release (as well as a 'QuietLogHandler' as a real class)
