### ISSUE TITLE
Specify Content Type in HTTP Post

### ISSUE THREAD

**Issue by copernicuswong** [rhuss/jolokia#288]
Hi,

Current it seems there is no way to specify the content type in the HTTP Post Request in Java Client.  I have created my J4pRequestHandler with

> ```
>    @Override
>     public HttpUriRequest getHttpRequest(J4pRequest pRequest, String pPreferredMethod, Map<J4pQueryParameter, String> pProcessingOptions) throws UnsupportedEncodingException, URISyntaxException
>     {
>         HttpUriRequest request = super.getHttpRequest(pRequest, pPreferredMethod, pProcessingOptions);
>         request.addHeader(HTTP.CONTENT_TYPE, ContentType.APPLICATION_JSON.getMimeType());
>         return request;
>     }
> 
>    @Override
>     public <T extends J4pRequest> HttpUriRequest getHttpRequest(List<T> pRequests, Map<J4pQueryParameter, String> pProcessingOptions) throws UnsupportedEncodingException, URISyntaxException
>     {
>         HttpUriRequest request = super.getHttpRequest(pRequests, pProcessingOptions);
>         request.addHeader(HTTP.CONTENT_TYPE, ContentType.APPLICATION_JSON.getMimeType());
>         return request;
>     }
> ```

Of course, it would be good to make it configurable, such as putting it in ProcessingOptions.  What do you think?  Or could you let me know if there is a smarter way to do it?

Thanks

**Comment by rhuss** [comment]
The question is, whether we really need it to make configurable. We know on the other side there is a Jolokia agent and currently it doesn't use the content type sent by the client. So the the content type is irrelevant at the moment.

I could be wrong, too ;-) What is your use case ?

**Comment by copernicuswong** [comment]
Our server takes the content-type into account to distinguish the type of protocol it is using so in my case, I will need to add "application/json" in the header.  Maybe it is just a rare case.
