### ISSUE TITLE
Would like to be able to specify the error response when rejecting access

### ISSUE THREAD

**Issue by jagaudet** [rhuss/jolokia#297]
If the root element of the policy file has a "granting-privileges" attribute, and an authenticated user does not have any of the privileges listed in that attribute, the error message in the response indicates that remote access is not allowed.  This is due to the isRemoteAllowed() check being:
`
boolean isRemoteAllowed() { return hasPrivilegesInRootNodeOfXml() && isAccessAllowedFrom(remoteEndpoint); }
`
It seems like there should be a separate check for "hasPrivilegesInRootNodeOfXml()", with its own error response.

**Comment by rhuss** [comment]
Sorry, don't get it. Could you post an example what you a refering to and what your environment and context is ? Vanilla Jolokia has neither a `isRemoteAllowed()` nor a `hasPrivilegesInRootNodeOfXml()` .....

**Comment by jagaudet** [comment]
Sorry, apparently I was confused by a code snippet someone sent me explaining the issue.  It turns out it's in our restrictor, not jolokia.  At best, this is an improvement request for the ability to specify a custom error message when rejecting access.

**Comment by rhuss** [comment]
Where would you like to specify the error message ? Could you please elaborate a bit on your use case ?

In general I'm not positive for returning **why** a check fails to the client as it possibly can be used for probing. If you want to log it to your log, let your custom restrictor do it.

If you dont mind I'm going to close this issue. Feel free to reopen it with a description of your use case and why such an error response would be helpful.

**Comment by jagaudet** [comment]
I've updated the original comment, but apparently can only re-open if I was the one who closed it.  I certainly agree that returning "why" is information leakage, but the existing behaviour seems to be prone to that.  From that perspective, that we have to leak mis-information is at least a little amusing.

**Comment by jagaudet** [comment]
Hmm, I suppose we can put anything custom within "isTypeAllowed", as that response is generic enough as-is.
