### ISSUE TITLE
http://10.0.128.102:7777/jolokia/read/Catalina:name=%22http-bio-7070%22,type=ThreadPool

### ISSUE THREAD

**Issue by zhaiyuyong** [rhuss/jolokia#299]
{"error_type":"java.lang.IllegalStateException","error":"java.lang.IllegalStateException : Error while extracting ooBInline from org.apache.tomcat.util.net.SocketProperties@1d9caffc","status":500,"stacktrace":"java.lang.IllegalStateException: Error while extracting ooBInline from org.apache.tomcat.util.net.SocketProperties@1d9caffc\n\tat org.jolokia.converter.json.BeanExtractor.extractBeanPropertyValue(BeanExtractor.java:276)\n\tat org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:184)\n\tat org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)\n\tat org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)\n\tat org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)\n\tat org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)\n\tat org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)\n\tat org.jolokia.converter.json.MapExtractor.extractMapValues(MapExtractor.java:75)\n\tat org.jolokia.converter.json.MapExtractor.extractObject(MapExtractor.java:65)\n\tat org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)\n\tat org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)\n\tat org.jolokia.converter.json.ObjectToJsonConverter.extractObjectWithContext(ObjectToJsonConverter.java:207)\n\tat org.jolokia.converter.json.ObjectToJsonConverter.convertToJson(ObjectToJsonConverter.java:111)\n\tat org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:425)\n\tat org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)\n\tat org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)\n\tat org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:137)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.executePostRequest(JolokiaHttpHandler.java:270)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:224)\n\tat org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:169)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)\n\tat sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)\n\tat sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:677)\n\tat com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)\n\tat sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:649)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:606)\n\tat org.jolokia.converter.json.BeanExtractor.extractBeanPropertyValue(BeanExtractor.java:271)\n\t... 28 more\nCaused by: java.lang.NullPointerException\n\tat org.apache.tomcat.util.net.SocketProperties.getOoBInline(SocketProperties.java:223)\n\t... 32 more\n"}

**Comment by zhaiyuyong** [comment]
{
   "type":"read",
   "mbean":"Catalina:port=7070,type=Connector"
}
can get all attributes are read.

but

{
   "type":"read",
   "mbean":"Catalina:name=\"http-bio-7070\",type=ThreadPool",
   "attribute":"currentThreadCount"
}

can not

**Comment by rhuss** [comment]
Seems like there is a least one attribute of this MBean which throws an error during extraction of the value (where Java-JSON serialization is used). You can use an query parameter `?ignoreErrors=true` to get to the other values or you can limit your request to the set of values you are interested it.

There is no much Jolokia can do as it is the Tomcat bean itself which throws the error.

I'll close this issue for now, feel free to reopen if you think its still a Jolokia issue.
