### ISSUE TITLE
Jolokia does not discover my MBeans.

### ISSUE THREAD

**Issue by SyCode7** [rhuss/jolokia#303]
Hi, 
I am actually new to the jolokia, after following the examples at  [http://www.christophlorenz.de/blog/application-monitoring/](url) and  [https://jolokia.org/tutorial.html](url), I thought jolokia can automatically discover my existing MBeans but they have not been yest discovered . I still have the error `javax.management.InstanceNotFoundException`. Would there be some additional configuration ? Thanks.

**Comment by rhuss** [comment]
It depends on which `MBeanServer` you register your MBeans. This `MBeanServer` needs to found by the Jolokia agent, so its the best if you register your own MBeans on a well known MBeanServer. 

A safe bet is to use `ManagementFactory.getPlatformMBeanServer()` and register your MBeans there.

On which MBeanServer do you register your MBeans ?

**Comment by SyCode7** [comment]
I basically used the examples from the official JMX website [http://docs.oracle.com/javase/tutorial/jmx/](url) . as shown inthe snipper below - 
`
MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();

	// Construct the ObjectName for the Hello MBean we will register
	ObjectName mbeanName = new ObjectName("com.example:type=Hello");

	// Create the Hello World MBean
	Hello mbean = new Hello();

	// Register the Hello World MBean
	mbs.registerMBean(mbean, mbeanName);
       // modified here by adding the invocation based on [http://www.christophlorenz.de/blog/application-monitoring/](url)
	mbs.invoke(mbeanName, "sayHello", null,null);

        // Construct the ObjectName for the QueueSampler MXBean we will register
        ObjectName mxbeanName = new ObjectName("com.example:type=QueueSampler");

        // Create the Queue Sampler MXBean
        Queue<String> queue = new ArrayBlockingQueue<String>(10);
        queue.add("Request-1");
        queue.add("Request-2");
        queue.add("Request-3");
        QueueSampler mxbean = new QueueSampler(queue);

        // Register the Queue Sampler MXBean
        mbs.registerMBean(mxbean, mxbeanName);

`

**Comment by rhuss** [comment]
If you do it like this, your MBean will be available via Jolokia.

You can use the "list" and "search" operation to look for it.

Or in your case you should be able to call 'http://.../jolokia/exec/com.example:type=Hello/sayHello' ...

**Comment by SyCode7** [comment]
Here is what I have done so far ... I restarted the MBean to be sure, and ran the command  `http://192.168.89.77:8081/jolokia/exec/com.example:type=Hello/sayHello` in the browser, the still no joy yet as shown in following error trace :  
`{"error_type":"javax.management.InstanceNotFoundException","error":"javax.management.InstanceNotFoundException : com.example:type=Hello","status":404,"request":{"operation":"sayHello","mbean":"com.example:type=Hello","type":"exec"},"stacktrace":"javax.management.InstanceNotFoundException: com.example:type=Hello\n\tat com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)\n\tat com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBeanInfo(DefaultMBeanServerInterceptor.java:1375)\n\tat com.sun.jmx.mbeanserver.JmxMBeanServer.getMBeanInfo(JmxMBeanServer.java:920)\n\tat org.jolokia.handler.ExecHandler.extractMBeanParameterInfos(ExecHandler.java:167)\n\tat org.jolokia.handler.ExecHandler.extractOperationTypes(ExecHandler.java:133)\n\tat org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:84)\n\tat org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:40)\n\tat org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:89)\n\tat org.jolokia.backend.MBeanServerExecutorLocal.handleRequest(MBeanServerExecutorLocal.java:109)\n\tat org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:102)\n\tat org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:98)\n\tat org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:411)\n\tat org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)\n\tat org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)\n\tat org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:86)\n\tat org.jolokia.http.AgentServlet$4.handleRequest(AgentServlet.java:435)\n\tat org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:320)\n\tat org.jolokia.http.AgentServlet.handle(AgentServlet.java:291)\n\tat org.jolokia.http.AgentServlet.doGet(AgentServlet.java:252)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:620)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:727)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)\n\tat org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)\n\tat org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n\tat java.lang.Thread.run(Thread.java:745)\n"}`

Is there a preference in the location from where I should run the MBean ?


`http://192.168.89.77:8081/jolokia/list` also didn't help !

**Comment by rhuss** [comment]
@SyCode7 How did you connect the agent to the main program ? It looks like you are using a servlet container, right ? Did you adapt the example that it registers the MBean during a servlet's init() method ? (because the vanilla example uses a standalone app with `public static void main(String[] args)`)

**Comment by SyCode7** [comment]
Hi, I am not sure how to do that, can you give me an example or reference ? I enabled discovery as mentioned in the documentation [https://jolokia.org/reference/html/agents.html#agents-war](url)

**Comment by rhuss** [comment]
The best way to try things out is to use the Oracle example with the `Main` class, compile it and then use the JVM agent of Jolokia as described in https://jolokia.org/agent/jvm.html :

```
java -javaagent:jolokia-agent.jar -cp . Main
```

This is better suited for a standalone class. If you would have a web application and therefor need a Servlet container anyway, then the war agent is easier to install.

**Comment by SyCode7** [comment]
Sure, I will go through the tutorials again.
Many thanks :+1:
