### ISSUE TITLE
Error verifying datasource type "GridLink" in weblogic

### ISSUE THREAD

**Issue by adrianoguilhermetti** [rhuss/jolokia#311]
Hi, 

Recently I started to monitor datasources in Weblogic. 
So far the datasources were "Generic" type and that's fine. 
But now we have some datasource of type "GridLink" and Jolokia returns error when checking them. 
See the test below: 

DATASOURCE "GENERIC" TYPE: 
[Root @ srv13 check] # / usr / local / bin / check_jmx4perl --url http://10.142.9.108:8001/jolokia-war-1.3.5 --mbean com.bea: ServerRuntime = soa_server1, Name = gesplan_wfnPOOL, Type = JDBCDataSourceRuntime --attribute State --perfdata = no --label% v --timeout 30 
OK - Running 
[Root @ srv13 check] # 

DATASOURCE TYPE "GRIDLINK": 
[Root @ srv13 check] # / usr / local / bin / check_jmx4perl --url http://10.142.9.108:8001/jolokia-war-1.3.5 --mbean com.bea: ServerRuntime = soa_server1, Name = OraSDPMDataSource, Type = JDBCDataSourceRuntime --attribute State --perfdata = no --label% v --timeout 30 
UNKNOWN - Error: 404 javax.management.InstanceNotFoundException: com.bea: ServerRuntime = soa_server1, Name = OraSDPMDataSource, Type = JDBCDataSourceRuntime 
[Root @ srv13 check] # 

Does anyone know if Jolokia does not support the "GridLink" datasource? 
Or what can be done, I mean, does it have any parameters that I must pass in the above commands telling the datasource type? 

Thank you!

**Comment by rhuss** [comment]
The error shown above mean that there is no MBean `com.bea:ServerRuntime=soa_server1,Name = OraSDPMDataSource,Type=JDBCDataSourceRuntime` registered at the server. This can have of course a multitude of reasons.  (one of them could be an error in the spelling, the 'Name' looks suspicious to me)

Best starting point of debugging this is to get the list of registered MBeans and grep for the MBean you are interested in:

```
jmx4perl http://10.142.9.108:8001/jolokia-war-1.3.5 list
```

btw, I highly recommend to protect your Jolokia access at least with user and password.

**Comment by adrianoguilhermetti** [comment]
Hi rhuss, 

First of all thank you for your return.

The output of the command you sent:
Jmx4perl http://10.142.9.108:8001/jolokia-war-1.3.5 list
It helped a lot

I analyzed the salts for each of the data and responses:
Yes, MBEAN really is different:
-For the GENERIC type datasource the MBEAN is: JDBCDataSourceRuntime
-For the datasource type GRIDLINK the MBEAN is: JDBCOracleDataSourceRuntime

Thanks a lot for the help!
