### ISSUE TITLE
Provide implementation of MBeanServerConnection for Jolokia

### ISSUE THREAD

**Issue by apupier** [rhuss/jolokia#313]
It would be nice to provide an implementation of MBeanServerConnection for Jolokia.
It will allow to reuse almost all JMX clients (at least the one respecting the usage of the Java interface).

An implementation has been started here https://github.com/jbosstools/jbosstools-server/blob/3cbc12826db37e57a770bd723289cc6d5b68f019/jmx/plugins/org.jboss.tools.jmx.jolokia/src/org/jboss/tools/jmx/jolokia/internal/connection/JolokiaMBeanServerConnection.java

**Comment by apupier** [comment]
this improvement is required first: https://github.com/rhuss/jolokia/issues/317

**Comment by apupier** [comment]
I think it has the same goal than the JSR-160 implementation

**Comment by rhuss** [comment]
@skarsaune I think this actually exactly what you have implemented with a JMX connector ?

**Comment by apupier** [comment]
Eveyrbody agrees. Closing this enhancement request then :-)
