### ISSUE TITLE
Read GET Request with multiple JMX MBean entries

### ISSUE THREAD

**Issue by flowei** [rhuss/jolokia#330]
Hi there.
I'm using jolokia jvm agent 1.3.6 and metricbeat jolokia module to parse jmx metrics of a tomcat 7.0.41 server.
When I launch a **list** GET request to jolokia, I can see 3 datasources listed (2 of them in the jolokia list extract json output below). 

To be compliant with metricbeat jolokia module functionning, I'm trying to get the corresponding datasources attributes through a **READ** GET request, but I can't find the right syntax to do so.
I either get a **java.lang.IndexOutOfBoundsException** or a **javax.management.InstanceNotFoundException**.

Have you any tips to do so? Thanks for your help.

Jolokia list GET request json output extract (I'm able to parse GC entries attributes with metricbeat jolokia module but not Datasource attributes) :

```
"request": {
  "type": "list"
},
"status": 200,
"timestamp": 1499353927,
"value": {
  "Catalina": {
    "class=javax.sql.DataSource,context=/akuiteo,host=localhost,name=\"jdbc/V9GestionDS\",type=DataSource": {
      "attr": {
        "accessToUnderlyingConnectionAllowed": {
          "desc": "Introspected attribute accessToUnderlyingConnectionAllowed",
          "rw": true,
          "type": "boolean"
        }
      },
      "class": "org.apache.tomcat.util.modeler.BaseModelMBean",
      "desc": null
    },
    "class=... ,context=/akuiteo.clients,host=...,name=\"jdbc/V9GestionDS\",type=DataSource": {
      "attr": {
        "accessToUnderlyingConnectionAllowed": {
          "desc": "Introspected attribute accessToUnderlyingConnectionAllowed",
          "rw": true,
          "type": "boolean"
         }
       }
     }
  }
  "java.lang": {
     "name=PS MarkSweep,type=GarbageCollector": {
       "attr": {
         "CollectionCount": {
           "desc": "CollectionCount",
           "rw": false,
           "type": "long"
         },
         "CollectionTime": {
           "desc": "CollectionTime",
           "rw": false,
           "type": "long"
          }
       },
       "class": "sun.management.GarbageCollectorImpl",
       "desc": "Information on the management interface of the MBean"
      },
      "name=PS Scavenge,type=GarbageCollector": {
        "attr": {
          "CollectionCount": {
            "desc": "CollectionCount",
            "rw": false,
            "type": "long"
          },
          "CollectionTime": {
            "desc": "CollectionTime",
            "rw": false,
            "type": "long"
          }
        },
        "class": "sun.management.GarbageCollectorImpl",
        "desc": "Information on the management interface of the MBean"
      }
    }
  }
```

**Comment by rhuss** [comment]
What exactly did you try to read the datasources ?

**Comment by flowei** [comment]
I tried different syntaxes through metricbeat jolokia module conf yml file and directly from a web browser based on what I get as a result of a list GET request and what I found in the doc (https://jolokia.org/reference/html/protocol.html#get-request).

Examples through a browser :
- http://hostname:8778/jolokia/read/Catalina:class=javax.sql.DataSource,context=//akuiteo,host=localhost,type=DataSource ==> IndexOutOfBoundsException

- http://hostname:8778/jolokia/read/Catalina:class=javax.sql.DataSource,context=/akuiteo,host=localhost,type=DataSource ==> InstanceNotFoundException

- http://hostname:8778/jolokia/read/Catalina:class=javax.sql.DataSource,context=!/akuiteo,host=localhost,type=DataSource ==> InstanceNotFoundException

- http://hostname:8778/jolokia/read/java.lang:name=PS%20MarkSweep,type=GarbageCollector ==> OK

**Comment by rhuss** [comment]
If you need to escape the '/' as descibed in the documentation, which you did in your third example. But there you forgot the "name=" part (like in the other examples, too)

**Comment by flowei** [comment]
My bad, I did try with the name but didn't notice that the exception wasn't the same :
javax.management.RuntimeOperationsException,"error":"javax.management.RuntimeOperationsException : Exception invoking method loginTimeout"
I will investigate on authentication from there.

**Comment by rhuss** [comment]
This exception results from an error on calling the JMX operation. Its nothing Jolokia can help much as it comes from Tomcat directly.

**Comment by flowei** [comment]
Sure, thanks for your help and work on Jolokia!
