### ISSUE TITLE
Support BigInteger as return type for method Invocation

### ISSUE THREAD

**Issue by apupier** [rhuss/jolokia#334]
it is currently returning a JSonOBject with value {"lowestSetBit"=1L}

**Comment by chemeugene** [comment]
+1

**Comment by rhuss** [comment]
Agreed. A bit busy these, happy to take pull requests.

**Comment by rhuss** [comment]
Its about writing a simplifier like the UrlSimplifier and register it in "META-INF/simplifiers-default"

**Comment by apupier** [comment]
sounds like it was implemented a while ago.

closing
