### ISSUE TITLE
Jolokia integration with kafka

### ISSUE THREAD

**Issue by aliartiza75** [rhuss/jolokia#365]
Hello everyone.

I am trying to get the Kafka related metrics using Jolokia. I am successful to extract the metrics for 
zookeeper but can't figure it out for the broker metrics retrieval. Like when I use this url

        http://localhost:8778/jolokia/list

I get metrics related to zookeeper but not for the Kafka broker.
    
Does anyone here have done something like this before, help will be appreciated. 

Thanks in advance!

**Comment by rhuss** [comment]
@aliartiza75 actually as Jolokia is only about exposing (arbitrary) JMX MBeans and is completely agnostic _which_ MBeans we are not of big help here. Its probably much better to ask the Kafka Community how to expose metrics via JMX (I guess this is a configuration option). As soon as JMX is enabled it should be visible with Jolokia.

As I'm a Kafka noob I'm still wondering whether Zookeeper and Kafka are running in the same JVM. Is this really the case ?

Nevertheless, please do understand that I close this issue for now. If there is something with a Jolokia specific twist, please feel free to reopen it.

**Comment by aliartiza75** [comment]
Thank you rhuss
