### ISSUE TITLE
Use different implementation for ChunkedWriter

### ISSUE THREAD

**Issue by rhuss** [rhuss/jolokia#366]
As part of #243 parts of StreamEncoder were taken over directly. Instead we have to implement that functionality differently, ideally without referring to another third party library.

Deriving from sun.nio.cs.StreamEncoder should be also no option as this is considered to be a private API.

// @gnufied

**Comment by dejanb** [comment]
This looks similar to the issue we had in https://issues.apache.org/jira/browse/AMQ-6651. Maybe we can leverage some code from Harmony to do this.

**Comment by rhuss** [comment]
Fixed with #371
