### ISSUE TITLE
Jolokia java jvm agent - issue with Metricbeat jolokia module

### ISSUE THREAD

**Issue by KrasnovNikita** [rhuss/jolokia#377]
I want to monitor jvm health of Elasticsearch 6x with the help of jolokia java jvm agent 1.5.0. For taking all metrics from Jolokia I use Metricbeat-6.2.3 and then will put all of them to Elasticsearch. Everything is installed on Windows system.
But right know I have some problems with installing jolokia jvm agent according to the instractions - https://jolokia.org/reference/html/agents.html#agents-jvm:

1) I've downlanded jvm agent http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/1.5.0/jolokia-jvm-1.5.0-agent.jar

2) then try to install with command: *java -javaagent:./jolokia-jvm-1.5.0-agent.jar=port=7777,host=localhost* 
but instead of success message with the full URL which can be used by clients for contacting the agent I get this:

    Usage: java [-options] class [args...]
               (to execute a class)
       or  java [-options] -jar jarfile [args...]
               (to execute a jar file)
    where options include:
        -d32          use a 32-bit data model if available
        -d64          use a 64-bit data model if available
        -server       to select the "server" VM
                      The default VM is server.
    
        -cp <class search path of directories and zip/jar files>
        -classpath <class search path of directories and zip/jar files>
                      A ; separated list of directories, JAR archives,
                      and ZIP archives to search for class files.
        -D<name>=<value>
                      set a system property
        -verbose:[class|gc|jni]
                      enable verbose output
        -version      print product version and exit
        -version:<value>
                      Warning: this feature is deprecated and will be removed
                      in a future release.
                      require the specified version to run
        -showversion  print product version and continue
        -jre-restrict-search | -no-jre-restrict-search
                      Warning: this feature is deprecated and will be removed
                      in a future release.
                      include/exclude user private JREs in the version search
        -? -help      print this help message
        -X            print help on non-standard options
        -ea[:<packagename>...|:<classname>]
        -enableassertions[:<packagename>...|:<classname>]
                      enable assertions with specified granularity
        -da[:<packagename>...|:<classname>]
        -disableassertions[:<packagename>...|:<classname>]
                      disable assertions with specified granularity
        -esa | -enablesystemassertions
                      enable system assertions
        -dsa | -disablesystemassertions
                      disable system assertions
        -agentlib:<libname>[=<options>]
                      load native agent library <libname>, e.g. -agentlib:hprof
                      see also, -agentlib:jdwp=help and -agentlib:hprof=help
        -agentpath:<pathname>[=<options>]
                      load native agent library by full pathname
        -javaagent:<jarpath>[=<options>]
                      load Java programming language agent, see java.lang.instrument
        -splash:<imagepath>
                      show splash screen with specified image
    See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.

3) then I try to attach to some java process with the help of such commands: 

    PS C:\Users\Kai Anton\Desktop> java -jar ./jolokia-jvm-1.5.0-agent.jar list
    11920   org.jetbrains.jps.cmdline.Launcher C:/Program Files/JetBrains/IntelliJ IDEA 2017.2.4/lib/aether-depe
    13252
    2456   ./jolokia-jvm-1.5.0-agent.jar list
    5308   org.jetbrains.jps.cmdline.Launcher C:/Program Files/JetBrains/IntelliJ IDEA 2017.2.4/lib/aether-depe
    PS C:\Users\Kai Anton\Desktop> java -jar ./jolokia-jvm-1.5.0-agent.jar start 11920
    Couldn't start agent for PID 11920
    Possible reason could be that port '8778' is already occupied.
    Please check the standard output of the target process for a detailed error message.

4) but then when I try to start it one more time with command *PS C:\Users\Kai Anton\Desktop> java -jar ./jolokia-jvm-1.5.0-agent.jar start 11920*  it returns *Jolokia is already attached to PID 11920
http://127.0.0.1:8778/jolokia/*

How I can check if Jolokia is installed? What I'm doing wrong?
P.S. Metricbeat Jolokia module is configured already and can take all information from jvm module. But in Metricbeat I don't see anything about Elastic jvm metrics.

**Comment by rhuss** [comment]
@KrasnovNikita maybe that's better a question for Metricbeat ?

2. can not work because you don't specify a class or jar to start to which the agent should be attached
3. Not sure why you want to attach to IntelliJ but it could be that you tried the command twice ? (so that the second time its doesnt work because there is already an agent attached).

You can try this by going with your browser to the provide URL. What do you see ?

If so, you are ready to monitor IntelliJ with anything which knows the Jolokia procotol, including Metricbeat.

Maybe the documentation at https://jolokia.org/reference/html/index.html is helpful for you, too ?

**Comment by KrasnovNikita** [comment]
Have more correct question right here - https://github.com/rhuss/jolokia/issues/378
