### ISSUE TITLE
Distribute two war agents: Secured with role "jolokia.war" and a "jolokia-insecure.war"

### ISSUE THREAD

**Issue by rhuss** [rhuss/jolokia#382]
In order to promote only a secured usage of the Jolokia agents is, that the default agent "jolokia.war" is secured by default with a role 'jolokia' starting with 1.6.0. In addition, to allow a quick installation for jolokia a 'jolokia-insecure.war' is distributed, too. 

That way, when someone does a plain update he will get now the secured agent and has to either enable a security setup for the servlet container or copy over 'jolokia-insecure.war'.

**Comment by rhuss** [comment]
Happend in 1.6.0

**Comment by mihamimi** [comment]
Where do I find the insecure war? Thanks

**Comment by rhuss** [comment]
It's in the binary distro at https://github.com/rhuss/jolokia/releases/download/v1.6.0/jolokia-1.6.0-bin.tar.gz and you can download it from Maven central, too.

**Comment by rhuss** [comment]
It's called `jolokia-unsecured.war` btw.

**Comment by mihamimi** [comment]
Thanks. I haven't find the artefact in the maven central.

**Comment by rhuss** [comment]
@mihamimi http://repo1.maven.org/maven2/org/jolokia/jolokia-war-unsecured/1.6.0/
