### ISSUE TITLE
Jolokia uses JRE 1.8 classes while supporting 1.6

### ISSUE THREAD

**Issue by tuijldert** [rhuss/jolokia#388]
Importing sources into Eclipse, it starts complaining about missing `java.beans.Transient` classes.
This is correct as that is not part of JRE 1.6, only of 1.8.

Jolokia 1.6.0. therefore does not support JRE 1.6.

**Comment by rhuss** [comment]
@tuijldert if you feel fancy, you could try out to build from branch `pr/java-1.6` to verify that it really works with Java 1.6 (and JBoss 5).

BTW, I though that JBoss 5 at least runs with Java 7 (and afaik Jolokia is also able to run with Java 1.7 up to the latest version)

**Comment by tuijldert** [comment]
I feel **very** fancy indeed, @rhuss. Works like a charm. As far as I'm concerned, 1.6.1 is a go 👍.

Wrt. JBoss, all I could find (Google) is a "Redhat JBoss EAP 5.2" version that was made available for Java 7, the JBoss 5.1 community version was tested but apparently gave SOAP an indigestion.
Still, I'll give it a whirl, see what gives...

Thanks for an awesome package btw. :)
