### ISSUE TITLE
Cannot read attributes with commas, are there any workarounds?

### ISSUE THREAD

**Issue by mayrstefan** [rhuss/jolokia#395]
This week we had issues with an application that had some MBean attribute names changed. They now contain a comma. Now I've found the following comment in the source code:
```
    /**
     * Constructor for GET requests
     *
     * @param pObjectName object name of MBean to read attributes from
     * @param pAttribute a one or more attribute to lookup. Can be null in which case all attributes
     *                   are to be fetched. More than one attribute can be provided by giving it a comma
     *                   separated list (attribute names with commas can not be use here, though).
     * @param pPathParts optional path parts from for filtering the return value
     * @param pInitParams optional processing parameters
     * @throws MalformedObjectNameException if the name is not a proper object name.
     */
    JmxReadRequest(String pObjectName,String pAttribute,List<String> pPathParts,
```

Is there a known escaping trick to make attributes with commas work?

**Comment by rhuss** [comment]
There is a way by escaping the comma with a `\` (use a "\\" when within a string)

**Comment by rhuss** [comment]
Let me know if this works for you.

**Comment by mayrstefan** [comment]
That worked. Thank you

In the jolokia REST API call we had to use `\,`. Expanding that to `\\,` pointed us into the right direction: on the command line with check_jmx4perl we had to escape it as `\\\\,`.

Is this documented anywhere or did we just miss it?
