### ISSUE TITLE
Jolokia agent affects application classloader

### ISSUE THREAD

**Issue by bgabrhelik** [rhuss/jolokia#398]
If application uses  com.googlecode.json-simple:json-simple:1.1.1 and jolokia is added as a javaagent, the classloader loads org.json.simple.JSONObject from jolokia bundle i.e. version 1.1.

I believe that java agents should load support classes by a special classloader so they don't affect an application, even if they brake visibility and uniqueness classloader principle.

Here  are related links:
https://javarevisited.blogspot.com/2012/12/how-classloader-works-in-java.html
https://www.voxxed.com/2015/12/class-loader-magic-how-to-write-a-java-agent

**Comment by bgabrhelik** [comment]
Well, later we found out that this issue was found on version 1.2 and the latest version 1.6 uses com.googlecode.json-simple:json-simple:1.1.1, however I believe the key problem here is isolation of jolokia dendencies from application classloader.

**Comment by rhuss** [comment]
I agree with you that the agent should be as less intrusive as possible. However, using different class loader is a bit difficult, so I would prefer to use a relocation of packages fo json-simple when packaging up the agent. I think that a simpler and more straight forward solution.

You might in similar problems when using Jolokia programmatically also within your code (+ the agent attached), so we might even consider relocating everything for the final agent.

Not sure whether there is tool support, but that would be worth checking out.

**Comment by bgabrhelik** [comment]
Relocation into another package sounds good. But Isolated classloader doesn't look very complicated in the link above.
https://www.voxxed.com/2015/12/class-loader-magic-how-to-write-a-java-agent

**Comment by rhuss** [comment]
Using a different is not difficult, but I'm afraid that there will be interference with the MBean classloader when looking up MBeans that have been loaded by a different classloader. More a feeling though.

However, if I would have enough time to spent on Jolokia these days, I would first move it to Java 11 which a more pressing issue these days. Relocation looks like an easy thing as it doesn't require any Java code changes (except a post-build step).

Happy to review and integrate any PR here.

**Comment by jerboaa** [comment]
FYI: I've proposed a PR for this. Perhaps that's something worth having?

**Comment by BernalCarlos** [comment]
Hello, 

Seems like one check is missing on the PR. Any updates on this?

Thanks.

**Comment by grgrzybek** [comment]
For late visitors, #413 unintentionally removed the `agent` classifier from the `jolokia-jvm` artifact.

With maven-assembly-plugin, `<id>agent</id>` in the assembly descriptor created new artifact attached to the reactor, so we have https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar

With maven-shade-plugin, the original `jolokia-jvm` is actually replaced with the shaded version, so https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.7.2/jolokia-jvm-1.7.2.jar is the one, only and shaded version of the agent.
