### ISSUE TITLE
Add support to load multiple CA certs from store

### ISSUE THREAD

**Issue by dsimansk** [rhuss/jolokia#403]
It'd be great to add a support for multiple CA certs. 

https://github.com/rhuss/jolokia/blob/33b23e578e6e9dbb0604e3168732ceb332cbba9a/agent/jvm/src/main/java/org/jolokia/jvmagent/security/KeyStoreUtil.java#L55-L67

In fact it's a bug affecting latest versions of OpenShift. The same issue was fixed in openshift-ping. 
https://github.com/jboss-openshift/openshift-ping/pull/43

Cc @rhuss

**Comment by rhuss** [comment]
Valid point, thanks for spotting this ! Not sure whether you want to send in a PR, but if so, I could release the next version of jolokia over the weekend.

**Comment by dsimansk** [comment]
@rhuss I've created a PR, please take a look when it suits you. It's not so urgent as there's another issues on the OpenShift side. However, it might be good to have this one resolved just in case. :)

**Comment by rhuss** [comment]
Thanks a lot ! I will have a look ASAP, also because I guess it will take a bit until it bubbles up to the images using Jolokia. So I agree, that Jolokia should be ready soon.

**Comment by paoloantinori** [comment]
Hi Roland!

Do you have plans for a release anytime soon? We'd like to use this functionality for OpenShift 4 related setups.

**Comment by rhuss** [comment]
@paoloantinori I have no concrete plans but can do a release soonish. If there won't be a release until the end of the week, please ping me again.

**Comment by paoloantinori** [comment]
thank you!
