### ISSUE TITLE
Make multicast discovery address configurable

### ISSUE THREAD

**Issue by graben** [rhuss/jolokia#421]
Multicast address is actually hard coded to:
```
// IPv4 Address for Jolokia's Multicast group
public static final String JOLOKIA_MULTICAST_GROUP = "239.192.48.84";

// Multicast port where to listen for queries
public static final int JOLOKIA_MULTICAST_PORT = 24884;
```

This is problematic in large networks where discovery should be separated into clusters. Therefore, it would be helpful to explicitly config multicast address to agent.

**Comment by rhuss** [comment]
Fair point. Fancy to work on a PR ? 'would help to integrate it (but otherwise totally busy with day-to-day work)

**Comment by graben** [comment]
I will look to find some time for a PR.
