### ISSUE TITLE
Update json-simple 1.1.1  to avoid Junit as dependency

### ISSUE THREAD

**Issue by boly38** [rhuss/jolokia#426]
I noticed on my java project that if I add `org.jolokia:jolokia-core:jar:1.6.2` as dependency, 
then `com.googlecode.json-simple:json-simple:jar:1.1.1` is added as dependency.

So Jolokia rely on json-simple, but there is an anoying stuff with this version of json-simple : 
 junit is also added as dependency

I found this related issue:  fangyidong/json-simple#91

If confirmed, it would be great to try to switch to a newer version of json-simple to avoid this issue.

**Comment by rhuss** [comment]
Unfortunately, 1.1.1 is the latest version of json-simple.  I agree that the JUnit dependency is incorrect, however I think we could solve this by addign an <exclude> to the json-simple dependency.

**Comment by rhuss** [comment]
Sorry, I just checked the dependency tree  of jolokia-core:

```
[INFO] --- maven-dependency-plugin:2.9:tree (default-cli) @ jolokia-core ---
[INFO] org.jolokia:jolokia-core:jar:1.6.3-SNAPSHOT
[INFO] +- com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[INFO] +- javax.servlet:servlet-api:jar:2.4:provided
[INFO] +- org.jolokia:jolokia-test-util:jar:1.6.3-SNAPSHOT:test
[INFO] +- org.testng:testng:jar:6.8.8:test
[INFO] |  +- org.beanshell:bsh:jar:2.0b4:test
[INFO] |  \- com.beust:jcommander:jar:1.27:test
[INFO] +- org.easymock:easymock:jar:3.0:test
[INFO] |  +- cglib:cglib-nodep:jar:2.2:test
[INFO] |  \- org.objenesis:objenesis:jar:1.2:test
[INFO] \- org.jmockit:jmockit:jar:1.8:test
```

Not sure where you see junit ?

**Comment by rhuss** [comment]
Also, we **already** have an exclusion of the junit dependency included:

```xml
  <dependency>
        <groupId>com.googlecode.json-simple</groupId>
        <artifactId>json-simple</artifactId>
        <version>1.1.1</version>
        <exclusions>
          <!-- That's a bug in json-simple that junit is referenced without scope test -->
          <exclusion>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
```

**Comment by boly38** [comment]
Hi @rhuss 

>we already have an exclusion of the junit dependency included

My bad, you're absolutely right, **jolokia** is OK [since 21 May 2014](https://github.com/rhuss/jolokia/commit/f9b97f4b3eca9739bea4f361d67f9bdd263ef4f3)

I were unable to reproduce locally, because when I created this issue I were probably based on an old version of my product with an explicit `json-simple` dependency but without this exclusion tips. So nothing related to Jolokia itself. Jolokia rely on json-simple in a clean way (no junit in scope compile)

This issue must be closed
Sorry for this noise :)
thanks again
