### ISSUE TITLE
Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException

### ISSUE THREAD

**Issue by Maira11** [rhuss/jolokia#435]
Hi,
I've setup jolokia in my machine and it's running fine. I've installed POSTMAN and trying to send POST request to the server. I want to get some properties from JConsole, and JConsole is in remote desktop.
So in the JSON request, I've added a target key which has the url which I use to connect to Jconsole remotely. It is in the form, "service:jmx:rmi:///jndi/rmi://hostname:portnumber/jmxrmi".

But the response I get is,

Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: hostname; nested exception is: \n\tjava.net.ConnectException: Connection timed out: connect]\r\n\tat javax.management.remote.rmi.RMIConnector.connect(Unknown Source)\r\n\tat javax.management.remote.rmi.RMIConnector.connect(Unknown Source)\r\n\tat org.jolokia.jsr160.Jsr160RequestDispatcher.getConnector(Jsr160RequestDispatcher.java:101)\r\n\tat org.jolokia.jsr160.Jsr160RequestDispatcher.dispatchRequest(Jsr160RequestDispatcher.java:76)\r\n\tat org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:411)\r\n\tat org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)\r\n\tat org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)\r\n\tat org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:137)\r\n\tat org.jolokia.http.AgentServlet$3.handleRequest(AgentServlet.java:425)\r\n\tat org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:320)\r\n\tat org.jolokia.http.AgentServlet.handle(AgentServlet.java:291)\r\n\tat org.jolokia.http.AgentServlet.doPost(AgentServlet.java:259)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:660)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:741)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\r\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\r\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)\r\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\r\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)\r\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)\r\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)\r\n\tat org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)\r\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)\r\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\r\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)\r\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\r\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)\r\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)\r\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\r\n\tat java.lang.Thread.run(Unknown Source)\r\nCaused by: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: hostname; nested exception is: \n\tjava.net.ConnectException: Connection timed out: connect]\r\n\tat com.sun.jndi.rmi.registry.RegistryContext.lookup(Unknown Source)\r\n\tat com.sun.jndi.toolkit.url.GenericURLContext.lookup(Unknown Source)\r\n\tat javax.naming.InitialContext.lookup(Unknown Source)\r\n\tat javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(Unknown Source)\r\n\tat javax.management.remote.rmi.RMIConnector.findRMIServer(Unknown Source)\r\n\t... 36 more\r\nCaused by: java.rmi.ConnectException: Connection refused to host: hostname; nested exception is: \n\tjava.net.ConnectException: Connection timed out: connect\r\n\tat sun.rmi.transport.tcp.TCPEndpoint.newSocket(Unknown Source)\r\n\tat sun.rmi.transport.tcp.TCPChannel.createConnection(Unknown Source)\r\n\tat sun.rmi.transport.tcp.TCPChannel.newConnection(Unknown Source)\r\n\tat sun.rmi.server.UnicastRef.newCall(Unknown Source)\r\n\tat sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)\r\n\t... 41 more\r\nCaused by: java.net.ConnectException: Connection timed out: connect\r\n\tat java.net.DualStackPlainSocketImpl.connect0(Native Method)\r\n\tat java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)\r\n\tat java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)\r\n\tat java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)\r\n\tat java.net.AbstractPlainSocketImpl.connect(Unknown Source)\r\n\tat java.net.PlainSocketImpl.connect(Unknown Source)\r\n\tat java.net.SocksSocketImpl.connect(Unknown Source)\r\n\tat java.net.Socket.connect(Unknown Source)\r\n\tat java.net.Socket.connect(Unknown Source)\r\n\tat java.net.Socket.<init>(Unknown Source)\r\n\tat java.net.Socket.<init>(Unknown Source)\r\n\tat sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(Unknown Source)\r\n\tat sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(Unknown Source)\r\n\t... 46 more\r\n","error_type":"java.io.IOException","error":"java.io.IOException : Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: hostname; nested exception is: \n\tjava.net.ConnectException: Connection timed out: connect]","status":500}

Please help me solve this issue,
Thanks.

**Comment by rhuss** [comment]
Jolokia can't be accessed over RMI but over HTTP (that's the whole point of this project). Please check out www.jolokia.org for the documentation and how Jolokia works (and which problems it solved)

You can however run Jolokia as a proxy to RMI enabled server, so that a Jolokia client can talk to an non-jolokia (but JMX RMI) enabled server. But not vice versa (RMI client with Jolokia)

Also, when you use "hostname" literally that would never work, you should add your real JMX RMI enabled servername here.

If you wan to connect with jconsole or any other JMX client tool, then you do have to wait for #431 to get integrated.

**Comment by Maira11** [comment]
It's not "hostname", I just didn't mention the server name. 
Thank you very much!
