### ISSUE TITLE
[Bug report] I am getting 400 error from "inputs.jolokia2_agent" during fetching connectors_http from undertow subsystems through Telegraf agent

### ISSUE THREAD

**Issue by razzrsi** [rhuss/jolokia#444]
Always getting error :  E! [inputs.jolokia2_agent] Error in plugin: Unexpected status in response from target : 400

System info:
Telegraf Version: 1.14.3
Jolokia agent version : 1.6.0
O.S ; Redhat 7

here below the jolokia configuration mentioned in telegraf agent config file:

# # Read JMX metrics from a Jolokia REST agent endpoint
 [[inputs.jolokia2_agent]]
#   # default_tag_prefix      = ""
#   # default_field_prefix    = ""
#   # default_field_separator = "."
#
#   # Add agents URLs to query
   urls = ["http://10.67.192.44:8778/jolokia"]

    # name_prefix = "jboss."
#   # username = ""
#   # password = ""
#   # response_timeout = "5s"
#
#   ## Optional TLS config
 #tls_ca   = "/var/private/ca.pem"
 #tls_cert = "/var/private/client.pem"
 #tls_key  = "/var/private/client-key.pem"
#   # insecure_skip_verify = false
#
#   ## Add metrics to read
   [[inputs.jolokia2_agent.metric]]
     name  = "java_runtime"
     mbean = "java.lang:type=Runtime"
     paths = ["Uptime"]

[[inputs.jolokia2_agent.metric]]
    name  = "jvm_memory"
    mbean = "java.lang:type=Memory"
    paths = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]

  [[inputs.jolokia2_agent.metric]]
    name     = "jvm_garbage_collector"
    mbean    = "java.lang:name=*,type=GarbageCollector"
    paths    = ["CollectionTime", "CollectionCount"]
    tag_keys = ["name"]

  [[inputs.jolokia2_agent.metric]]
    name       = "jvm_memory_pool"
    mbean      = "java.lang:name=*,type=MemoryPool"
    paths      = ["Usage", "PeakUsage", "CollectionUsage"]
    tag_keys   = ["name"]
    tag_prefix = "pool_"

 [[inputs.jolokia2_agent.metric]]
    name  = "java_threading"
    mbean = "java.lang:type=Threading"
    paths = ["TotalStartedThreadCount", "ThreadCount", "DaemonThreadCount", "PeakThreadCount"]

 [[inputs.jolokia2_agent.metric]]
    name = "java_last_garbage_collection"
    mbean = "java.lang:name=*,type=GarbageCollector"
    paths = ["LastGcInfo"]
    tag_keys = ["name"]

 [[inputs.jolokia2_agent.metric]]
   name = "java_class_loading"
   mbean = "java.lang:type=ClassLoading"
   paths = ["LoadedClassCount", "UnloadedClassCount", "TotalLoadedClassCount"]

 [[inputs.jolokia2_agent.metric]]
   name     = "connectors_http"
   mbean    = "jboss.as:https-listener=*,server=*,subsystem=undertow"
   paths    = ["bytesReceived","bytesSent","errorCount","requestCount"]
  tag_keys = ["server","https-listener"]

[[inputs.jolokia2_agent.metric]]
   name     = "connectors_http"
   mbean    = "jboss.as:http-listener=*,server=*,subsystem=undertow"
   paths    = ["bytesReceived","bytesSent","errorCount","requestCount"]
   tag_keys = ["server","http-listener"]

 [[inputs.jolokia2_agent.metric]]
    name     = "datasource_jdbc"
    mbean    = "jboss.as:data-source=*,statistics=jdbc,subsystem=datasources"
    paths    = ["PreparedStatementCacheAccessCount","PreparedStatementCacheHitCount","PreparedStatementCacheMissCount"]
    tag_keys = ["data-source"]

 [[inputs.jolokia2_agent.metric]]
    name     = "datasource_pool"
    mbean    = "jboss.as:data-source=*,statistics=pool,subsystem=datasources"
    paths    = ["AvailableCount","ActiveCount","MaxUsedCount"]
    tag_keys = ["data-source"]

**Note : All key are working fine except undertow details. Means gathered matrices and stored in influxdb **

**Comment by rhuss** [comment]
Please boil that issue down on a pure Jolokia issue with concrete HTTP requests that are failing. We can't debug through a full toolchain. 

I can't offer support for Telegraf nor the concrete JBoss MBeans. Jolokia is only the messenger.

Hope you don't mind if I close the issue, feel free to reopen when you more concrete indication where Jolokia can help here.
