### ISSUE TITLE
jolokia jvm add to kafka server ,kafka can not start

### ISSUE THREAD

**Issue by qinzl1** [rhuss/jolokia#447]
vi kafka-server-start.sh

export JMX_PORT=9999
export RMI_HOSTNAME=log-services-250
export KAFKA_OPTS="$KAFKA_OPTS -javaagent:/data/kafka_2.11-1.1.0/libs/jolokia-agent.jar -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=$RMI_HOSTNAME -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT"

**Comment by qinzl1** [comment]
Failed to find Premain-Class manifest attribute in jolokia-jvm-1.6.2.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by rhuss** [comment]
Does Kafka come with a bundled version of Jolokia or is this something you copied over ? If so, be sure to use the proper agen jar file (there is one with dependencies and the proper manifest, and the other has only the agent classes)

**Comment by qinzl1** [comment]
@rhuss 
I don't see a description of compatibility，I've tried 1.3.7version it throw the same error

**Comment by rhuss** [comment]
How large is the jar that you are using ? (in bytes)

**Comment by qinzl1** [comment]
@rhuss 
93KB
![image](https://user-images.githubusercontent.com/20242930/92691112-a6e4f480-f374-11ea-8bab-3cce1a4a1052.png)

**Comment by rhuss** [comment]
that's the wrong jar. Use the one with the `jolokia-jvm.jar` from https://github.com/rhuss/jolokia/releases/download/v1.6.2/jolokia-1.6.2-bin.zip  Should be ~465k.

**Comment by rhuss** [comment]
or https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar ....

**Comment by qinzl1** [comment]
@rhuss 
The JAR file is correct, just renamed to jolokia-agent.jar

**Comment by qinzl1** [comment]
@rhuss 
![image](https://user-images.githubusercontent.com/20242930/92692169-54a4d300-f376-11ea-8189-7cdfaa0b2448.png)

**Comment by rhuss** [comment]
If its only 93k its not the right one, sorry.

**Comment by qinzl1** [comment]
@rhuss 
thx，so weird，I also downloaded it from the official website
