### ISSUE TITLE
Possible Integer overflow in OperationChecking

### ISSUE THREAD

**Issue by ryandgoulding** [rhuss/jolokia#459]
Per https://lgtm.com/projects/g/rhuss/jolokia/snapshot/5af274c465d19828fdbb4f5787b92d5d4cad7539/files/it/core/src/main/java/org/jolokia/it/OperationChecking.java?sort=name&dir=ASC&mode=heatmap#xfd12e45d383a8229:1

**Comment by rhuss** [comment]
thanks for the finding ! Sorry for the delay, I really work on Jolokia from time to time (where time is in the order of months right now).

Apologies. Closing this issue as the correspond PR is merged.
