### ISSUE TITLE
Release 1.7.0 - missing agents and clients ? 

### ISSUE THREAD

**Issue by Daryes** [rhuss/jolokia#469]
Hello,

Thanks for the update, but unless I missed something in the release notes, some agents weren't built in the 1.7.0 version : 
```
$ ls -1 jolokia-1.*/agents
jolokia-1.6.2/agents:
jetty-sslengine-6.1.24.jar
jetty-util-6.1.24.jar
jolokia-core-1.6.2.jar
jolokia-jsr160-1.6.2.jar
jolokia-jvm.jar
jolokia-mule.jar
jolokia-osgi-1.6.2.jar
jolokia-osgi-bundle.jar
jolokia-osgi.jar
jolokia-unsecured.war
jolokia.war
json-simple-1.1.1.jar
org.apache.felix.http.api-2.2.0.jar
org.apache.felix.http.base-2.2.0.jar
org.apache.felix.http.jetty-2.2.0.jar

jolokia-1.7.0/agents:
jolokia-mule.jar
jolokia-osgi-bundle.jar
jolokia-osgi.jar
jolokia-unsecured.war
jolokia.war
```
I have no problem with the version number dropped, but multiple agents, starting with the jvm, are missing.
It is also the same for the files under clients/java/

Source are `jolokia-1.6.2-bin.tar.gz `and `jolokia-1.7.0-bin.tar.gz` archives, taken from the releases of this repo, 
Same for the .tar.gz or .zip archive, by the way.

**Comment by rhuss** [comment]
There were some clean ups in 1.7.0 compared to 1.6.2:

* The non-agents jars (like util, core etc.) are not released anymore, as well as the dependency jars.
* The JVM agent is now called "jolokia-jvm.jar" (without "-agent" part). The original jolokia-jvm.jar that did not hold the dependencies is not released standalone anymore. 
* Also, for the clients, the dependencies were dropped, too.

The change for the JVM client was kind of introduced by an update of the assembly plugin which happened in the last year, the removal of the dependencies was intentional.

However, happy to discuss if more should be included, but then maybe the dependencies in a sub-directory (as putting it on the same level as the agents feels wrong)

**Comment by Daryes** [comment]
Thanks for the information.
But as stated : 

> multiple agents, starting with the jvm, are missing.

The "jolokia-jvm.jar" file is nowhere to be found in the tar.gz  (or zip) release. And I am talking about the full agent, Only the war or the OSGI are available. Check the directory list in the first post, ""jolokia-jvm.jar" is not present in the  jolokia-1.7.0-bin.tar.gz release file.

This one is handy for java processes that do not require an app server like tomcat.


For the dependencies, I cannot say, I didn't had a situation where they were required (or was informed about).
This said, if you can still generate them automatically, it might be better for other users to have them still available in a "tools"  directory, or related name, in the main tar.gz package

**Comment by rhuss** [comment]
Ah,  I see. Let me check and fix this with a 1.7.1 eventually .... Thanks for the heads up !

**Comment by rhuss** [comment]
In the meantime, you can download the JVM agent from https://search.maven.org/artifact/org.jolokia/jolokia-jvm/1.7.0/jar (check the "Downloads" button in the upper right corner)

**Comment by rhuss** [comment]
Well, I just re-download the bin archive and see the following agents included:

```
tar ztvf ~/Downloads/jolokia-1.7.0-bin.tar.gz | grep agents
-rw-r--r--  0 roland wheel  107562 Jul 26 22:26 jolokia-1.7.0/reference/html/agents.html
-rw-r--r--  0 roland wheel  348963 Jul 26 22:28 jolokia-1.7.0/agents/jolokia.war
-rw-r--r--  0 roland wheel  349059 Jul 26 22:28 jolokia-1.7.0/agents/jolokia-unsecured.war
-rw-r--r--  0 roland wheel  382198 Jul 26 22:30 jolokia-1.7.0/agents/jolokia-mule.jar
-rw-r--r--  0 roland wheel  438079 Jul 26 22:28 jolokia-1.7.0/agents/jolokia-osgi.jar
-rw-r--r--  0 roland wheel 1385663 Jul 26 22:28 jolokia-1.7.0/agents/jolokia-osgi-bundle.jar
-rw-r--r--  0 roland wheel  488370 Jul 26 22:29 jolokia-1.7.0/agents/jolokia-jvm.jar
```

So, the JVM agent is included (!?!)

**Comment by Daryes** [comment]
You're right.
I've downloaded it again, and the agent is present.
Even checked the command history, sources are the same. No idea about what happened.

Sorry for the trouble.
