### ISSUE TITLE
404 when downloading Jolokia agent from jolokia.org

### ISSUE THREAD

**Issue by erkexzcx** [rhuss/jolokia#470]
This link returns 404: https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/1.7.0/jolokia-jvm-1.7.0-agent.jar

**Comment by rhuss** [comment]
Thanks for the heads up, good find. The agent has been renamed to `jolokia-jvm-1.7.0.jar` (so without the `-agent` part). Need to fix the link.

**Comment by tusharsonawanes** [comment]
Same for me.

**Comment by tusharsonawanes** [comment]
This works for me - https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/1.7.0/jolokia-jvm-1.7.0.jar
