### ISSUE TITLE
Jolokia returns wrong content type

### ISSUE THREAD

**Issue by fabianfrz** [rhuss/jolokia#483]
Since the server is returning the wrong content type header, clients that require it for correct formatting or deserializing may fail.

# How is Jolokia instrumented / How to reproduce

```
java -javaagent:libraries/agent/jolokia-jvm-1.7.1.jar=port=7777,host=localhost -classpath 'config:libraries/*' com.example.Main param1 paream2
```

# Actual behaviour

Jolokia returns the content type as text/plain:

```
curl http://127.0.0.1:7777/jolokia/ -v
*   Trying 127.0.0.1:7777...
* Connected to 127.0.0.1 (127.0.0.1) port 7777 (#0)
> GET /jolokia/ HTTP/1.1
> Host: 127.0.0.1:7777
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Pragma: no-cache
< Date: Mon, 22 Nov 2021 07:39:49 GMT
< Transfer-encoding: chunked
< Content-type: text/plain; charset=utf-8
< Expires: Mon, 22 Nov 2021 06:39:49 GMT
< Cache-control: no-cache
< 
* Connection #0 to host 127.0.0.1 left intact
{"request":{"type":"version"},"value":{"agent":"1.7.1","protocol":"7.2","config":{"listenForHttpService":"true","maxCollectionSize":"0","authIgnoreCerts":"false","agentId":"10.0.0.1-10205-6537cf78-jvm","agentType":"jvm","policyLocation":"classpath:\/jolokia-access.xml","agentContext":"\/jolokia","mimeType":"text\/plain","discoveryEnabled":"true","streaming":"true","historyMaxEntries":"10","allowDnsReverseLookup":"true","maxObjects":"0","debug":"false","serializeException":"false","multicastGroup":"239.192.48.84","maxDepth":"15","authMode":"basic","authMatch":"any","canonicalNaming":"true","allowErrorDetails":"true","realm":"jolokia","includeStackTrace":"true","multicastPort":"24884","useRestrictorService":"false","debugMaxEntries":"100"},"info":{}},"timestamp":1637566789,"status":200}
```

Expected behaviour:

Content-Type header for JSON should be application/json.

**Comment by rhuss** [comment]
By default the content-type is "text/plain" to work around certain limitations of HTTP proxy at that time that usually filtered out "application/json" (afair, that was 2011). However, you can switch to "application/json" by setting the configuration option `mimeType` (or provide this as a request parameter).

See the docs at https://jolokia.org/reference/html/ for details.

**Comment by fabianfrz** [comment]
@rhuss Ok, i have found that here:
https://github.com/rhuss/jolokia/blob/913a35138235e8f53b31662b11b12992cf4bf702/agent/core/src/main/java/org/jolokia/config/ConfigKey.java#L170
https://github.com/rhuss/jolokia/blob/913a35138235e8f53b31662b11b12992cf4bf702/agent/jvm/src/test/java/org/jolokia/jvmagent/handler/JolokiaHttpHandlerTest.java#L89

So I guess it behaves wrong by the HTTP spec (wrong mime-type that describes what the content is) but correct the the Jolokia spec (mime-type is text/plain unless overridden to be application/json).
Would it make sense then, to change the default to JSON and allow plaintext as a fallback. I don't think any proxies out there would struggle with that nowadays as almost all web applications and websites transfer JSON data over XHR.

**Comment by rhuss** [comment]
> So I guess it behaves wrong by the HTTP spec (wrong mime-type that describes what the content is)

I wouldn't say that it behaves wrong as JSON is *also* `plain/text` (i.e. every JSON document is also a text document, but not every text document is a JSON document).

Tbh, I hesitate to switch the default because of possible backward compatibility issues that I can't foresee, but I would expect quite some considering the age of Jolokia and that it is still used in many productions sites so that I would still like to keep Jolokia updatable without changes when e.g. fixing CVEs (the only reason possibly for such installation to consider an update).

You can switch the default content type on a per-request basis, but also in the startup configuration of the agent, so that it is globally changed. That is what I would recommend for your use case.

**Comment by fabianfrz** [comment]
OK
