### ISSUE TITLE
How to configure basic authentication of Jolokia

### ISSUE THREAD

**Issue by bryantlin** [rhuss/jolokia#485]
Hi, 

I am pretty new to Jolokia so still learning many things about it. 

I recently deployed Jolokia and can connect to http://localhost:8080/jolokia/version. It pops up with username and password. I don't know where to set it. I tried to search for materials/links but still don't find anything. Could you please let me know how to create an user to log in through authentication? 

Thanks!

**Comment by rhuss** [comment]
For trying it out I recommend using https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war-unsecured/1.7.1/jolokia-war-unsecured-1.7.1.war for exploring. This is the WAR agent, but without password protection.

If you want to enable and test password protection (a must for production workloads), you should check the instructions on https://jolokia.org/agent/war.html and follow the link to the reference manual.

**Comment by bryantlin** [comment]
Thanks! The unsecured one worked so I am trying to use the secured one. I will take a look at the link. 

Thanks again.

**Comment by rhuss** [comment]
cool that it helped. closing this issue for now.
