### ISSUE TITLE
Jolokia2 weblogic.conf - Weblogic Specific Metrics not working

### ISSUE THREAD

**Issue by utsukprani** [rhuss/jolokia#490]
1. I started the Jolokia JVM Agent successfully and dynaically attached it to the weblogic sever process as follows:
    `java -jar jolokia-jvm-1.7.1.jar --host x.x.x.x 7876`

2. I added the below conf file in my tellegraf
`[[inputs.jolokia2_agent]]
 urls = ["http://x.x.x.x:8778/jolokia/"]
 name_prefix = "weblogic."
 name_override="custom_jolokia_weblogic_xxxx"

 [inputs.jolokia2_agent.tags]
    monitor = "JMX"
    level1 = "NONPROD"

### JVM Generic Metrics

 [[inputs.jolokia2_agent.metric]]
    name  = "OperatingSystem"
    mbean = "java.lang:type=OperatingSystem"
    paths = ["ProcessCpuLoad","SystemLoadAverage","SystemCpuLoad"]

 [[inputs.jolokia2_agent.metric]]
    name  = "jvm_runtime"
    mbean = "java.lang:type=Runtime"
    paths = ["Uptime"]

 [[inputs.jolokia2_agent.metric]]
    name  = "jvm_memory"
    mbean = "java.lang:type=Memory"
    paths = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]

### WLS Metrics

 [[inputs.jolokia2_agent.metric]]
    name = "JTARuntime"
    mbean = "com.bea:Name=JTARuntime,ServerRuntime=*,Type=JTARuntime"
    paths =["SecondsActiveTotalCount","TransactionRolledBackTotalCount","TransactionRolledBackSystemTotalCount","TransactionRolledBackAppTotalCount","TransactionRolledBackResourceTotalCount","TransactionHeuristicsTotalCount","TransactionAbandonedTotalCount","TransactionTotalCount","TransactionRolledBackTimeoutTotalCount","ActiveTransactionsTotalCount","TransactionCommittedTotalCount"]
    tag_keys   = ["ServerRuntime"]
    tag_prefix = "wls_"`

However now when I test the conf, I am not getting the weblogic specific metrics. I am only getting the others. Output of the test is below:
`2022-01-01T18:13:51Z I! Starting Telegraf 1.20.0
2022-01-01T18:13:51Z D! [agent] Initializing plugins
2022-01-01T18:13:51Z D! [agent] Starting service inputs
2022-01-01T18:13:51Z D! [agent] Stopping service inputs
2022-01-01T18:13:51Z D! [agent] Input channel closed
2022-01-01T18:13:51Z D! [agent] Processor channel closed
2022-01-01T18:13:51Z D! [agent] Processor channel closed
2022-01-01T18:13:51Z D! [agent] Stopped Successfully

weblogic.custom_jolokia_weblogic_xxxx,jolokia_agent_url=http://x.x.x.x:8778/jolokia/,level1=NONPROD,monitor=JMX ProcessCpuLoad=0.0013271863649063984,SystemCpuLoad=0.09316221948462643,SystemLoadAverage=0.78 1641060832000000000
weblogic.custom_jolokia_weblogic_xxxx,jolokia_agent_url=http://x.x.x.x:8778/jolokia/,level1=NONPROD,monitor=JMX Uptime=242102807 1641060832000000000
weblogic.custom_jolokia_weblogic_xxxx,jolokia_agent_url=http://x.x.x.x:8778/jolokia/,level1=NONPROD,monitor=JMX HeapMemoryUsage.committed=953155584,HeapMemoryUsage.init=536870912,HeapMemoryUsage.max=1908932608,HeapMemoryUsage.used=597336808,NonHeapMemoryUsage.committed=441737216,NonHeapMemoryUsage.init=2555904,NonHeapMemoryUsage.max=-1,NonHeapMemoryUsage.used=432062952,ObjectPendingFinalizationCount=0 1641060832000000000`

Below is my system info:
`
Telegraf 1.20
Weblogic 12.2.1
Jolokia 1.7.1
Red Hat Linux Enterprise 7.9
`

**Comment by rhuss** [comment]
Sorry, this really sounds like a telegraf question. I don't know how telegraf queries Jolokia (looks like that you are using a custom input `inputs.jolokia2_agent.metric` that I don't know. A general advise for troubleshooting is to find out with which HTTP requests Telegraph hits your agent and then try it manually yourself to find out any error messages.

**Comment by utsukprani** [comment]
> Sorry, this really sounds like a telegraf question. I don't know how telegraf queries Jolokia (looks like that you are using a custom input `inputs.jolokia2_agent.metric` that I don't know. A general advise for troubleshooting is to find out with which HTTP requests Telegraph hits your agent and then try it manually yourself to find out any error messages.

@rhuss thanks for your time and reply. I managed to make it work. Will close it.
