### ISSUE TITLE
Error in plugin: Unable to gather metrics for http://xx.xxx.xx.xxx:1111/jolokia: Response from url "http://xx.xxx.xx.xxx:1111/jolokia" has status code 403 (Forbidden), expected 200 (OK)

### ISSUE THREAD

**Issue by bryantlin** [rhuss/jolokia#498]
I am using jolokia2 agent and the following is the authentication part in telegraf.conf.

> [[inputs.jolokia2_agent]]
urls = ["http://xx.xxx.xx.xxx:1111/jolokia"]
username = "test"
password = "test123"
name_prefix = "weblogic."

Below is the error message:

> Error in plugin: Unable to gather metrics for http://xx.xxx.xx.xxx:1111/jolokia: Response from url "http://xx.xxx.xx.xxx:1111/jolokia" has status code 403 (Forbidden), expected 200 (OK)

Is my way of specifying the credentials correct? I am sure the credentials works as I saw results when I directly accessed to the url from my local, entering the credentials. Is there any other reason resulting in the error? Could that be related to any access/permission I need to grant on weblogic instance?

Thanks!

**Comment by rhuss** [comment]
Sorry, this is a telegraf question not a Jolokia question. You have probably more luck asking the author of the respective telegraf plugin.
