### ISSUE TITLE
Defining a whitelist of patterns for jsr160ProxyAllowedTargets init param

### ISSUE THREAD

**Issue by Eldainorn** [rhuss/jolokia#506]
Hello
I am using jolokia with success when trying to send a GET request to our legacy application (do not know the details on that end since I have not been working on it). I have been given a task to configure jolokia to only allow access to a single point in the legacy app, which I assume can be done using the jsr160ProxyAllowedTargets init parameter.
I am having a hard time understanding why my whitelist is not getting accepted by jolokia, when making a GET api call. Here is what I have done:

1. exploded jolokia war file
2. edited web.xml with
`<init-param>
      <description>
        Path to a white list of patterns which are matched against possible JMX service URL for incoming requests
      </description>
      <param-name>jsr160ProxyAllowedTargets</param-name>
      <param-value>/path/to/jolokia/deploy/jsr160-proxy-allowed-patterns.txt</param-value>
    </init-param>`
3.  repackaged war file then copied it to server
4. created a whitelist as defined in 2. and added a pattern to it like so `^.*flushCache.*$` (whole api url is like this: `http://10.122.5.60:1680/jolokia-1.7.1/exec/jboss.security:service=JaasSecurityManager/flushCache%28java.lang.String%29/BOAccess`
5. use postman to send a GET request to the url defined in 4. but I keep getting 404 error
`message /jolokia-1.7.1/exec/jboss.security:service=JaasSecurityManager/flushCache%28java.lang.String%29/BOAccess`

`description The requested resource (/jolokia-1.7.1/exec/jboss.security:service=JaasSecurityManager/flushCache%28java.lang.String%29/BOAccess) is not available.`

So the question is, am I using this allowed pattern whitelist in a completely wrong way or am I making a mistake somewhere ? What I wish to achieve is that jolokia allows a GET call to the flushCache but all other "endpoints" (for the lack of a better term) must not be available for access via jolokia tool.

Thanks in advance.

**Comment by Eldainorn** [comment]
Ok, I managed to make it work (finally), but it seems that whitelist is getting ignored or not read at all. I have set an absolute path to it in the web.xml, then put in a pattern in the same way as in the first post. Any ideas what I am doing wrong?

**Comment by Eldainorn** [comment]
Hey @rhuss. Since my post I have been digging quite a lot into the source code and have managed to figure out what was wrong with my approach. I managed to implement what I wanted, but in the end, it was decided that jolokia might not even be needed anymore since we changed the business strategy and the outline of the project. Thanks! :)

**Comment by rhuss** [comment]
@Eldainorn oh, I hope you still have enjoyed the journey to Jolokia land and I wish you all the best with the new direction of your project.

I hope you don't mind when I close the issue, please reopen in case you want to continue to work on this.
