### ISSUE TITLE
Connecting to a java process dynamically is failing

### ISSUE THREAD

**Issue by utsukprani** [rhuss/jolokia#511]
hi,
I am trying to use jolokia jvm-agent to dynamically connect to a running weblogic server.
so i started the jolokia agen as follows
`java -jar jolokia-jvm-1.7.1.jar --host _hostname_ --port 8779 <<PID>>`

however when I am running it i get the following error -
`20021: well-known file /tmp/.java_pid20021 is not secure: file should be owned by the current user (which is 1002) but is owned by 1001`

would appreciate some help here.
is there a way to overcome this issue ?

**Comment by utsukprani** [comment]
any way to overcome this .. @rhuss

**Comment by rhuss** [comment]
Sorry, haven't seen that issue before. Which version of Java are you using on which platform ?

**Comment by utsukprani** [comment]
hi @rhuss thanks for replying.
below are the details of my env

**Platform**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux"

**Java**
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 8.0.6.10 - pxa6480sr6fp10-20200408_01(SR6 FP10))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200402_443261 (JIT enabled, AOT enabled)
OpenJ9   - 35ef566
OMR      - 4bca4f4
IBM      - 55acf4a)
JCL - 20200407_01 based on Oracle jdk8u251-b08

**Comment by utsukprani** [comment]
Hi @rhuss ... Any idea

**Comment by rhuss** [comment]
You should verify that the UID of the user that tries to attach and align it with the UID of the process to which you want to attach. It looks like they differ (i.e., UID 1001 started the java process, and you try to attach via UID 1002 to the process). See also the help message or the user manual at https://jolokia.org/reference/html/agents.html#jvm-attach:

```
There are several possible reasons why attaching to a process can fail:
   * The UID of this launcher must be the very *same* as the process to attach to. It is not sufficient
     to be root.
   * The JVM must have HotSpot enabled and be a JVM 1.6 or later.
   * It must be a Java process ;-)
```

**Comment by utsukprani** [comment]
Hi @rhuss, thanks for your reply.
So this means that I will need to know the password the user (uid) as I
will need to ssh with that user and then start the Java agent to attach to
a running process.
It seems it might not be possible to  dynamically find a Java process and
attach to it as I must have the same uid and hence I also need the
password, so that I can ssh with that user/pwd and start my jolokia agent
to attach to this process. Right ?

**Comment by rhuss** [comment]
In principle, yes. That's a security limitation of Java's agent Attach API that we can't bypass.

Of course, you have several options to become the Java process' user without knowing the password:

* Be root and then `su <user>` 
* Use SSH with keys (recommended anyway)
* Already start the agent when you start the Java process as described in the documentation

I'm closing this issue as there is nothing we can do from Jolokia's side. Feel free to reopen it if you think otherwise.

**Comment by utsukprani** [comment]
Thanks @rhuss.
Appreciate your time and feedback.
Will try these suggestions.
