### ISSUE TITLE
create tags with jolokia

### ISSUE THREAD

**Issue by mehrdad2000** [rhuss/jolokia#513]
Hi
How can I create tag while using telegraf to send jolokia metrics to influxdb? 
related issue https://github.com/influxdata/telegraf/issues/11731

here is the current tags
![image](https://user-images.githubusercontent.com/26499665/187116047-bd47f91e-32a3-480b-9d60-412798cc7cc8.png)

need to add more tags for group by like this
![image](https://user-images.githubusercontent.com/26499665/187116094-5f280f38-8a2a-4ed8-a21e-4138c4c40011.png)

my telegraf config
```
[[inputs.jolokia2_agent.metric]]
name = “MyCustomMetric”
mbean = “AllBeans:category=Color,Name=*”
paths = [“TimeToLive”,“Metric1”,“Metric3”,“Active”,“TimeoutRate”,“Status”]
tag_keys = [“Name”,“Status”]
```

current output of curl:
```
curl http://ip/:port/jolokia-war-unsecured-1.6.2/read/AllBeans:Name=*,category=Color | jq ‘.’
“AllBeans:Name=Customer,category=Color”: {
“TimeToLive”: 1000,
“Metric1”: 40,
“Metric2”: 0,
“Metric3”: 0,
“Name”: “Customer”,
“Active”: true,
“Status”: “OK”,
```

current Influx cli result:
```
> show tag keys from MyCustomMetric
name: MyCustomMetric
tagKey
------
Name
host
jolokia_agent_url

```

any idea?
Thanks

**Comment by rhuss** [comment]
Sorry, this is a pure telegraf question as it refers to telegraf's integration of Jolokia. Closing this issue here, please reopen if there is anything that can be done from the Jolokia side.
