### ISSUE TITLE
Setting policyLocation denies every IP

### ISSUE THREAD

**Issue by robbevl** [rhuss/jolokia#541]
I tried setting the policyLocation to a custom XML file, but it just refuses any IP.

I copied the XML file from the ref manual (bar some modifications):

```
<?xml version="1.0" encoding="utf-8"?>

<restrict>

  <remote>
    <host>127.0.0.1</host>
  </remote>

  <http>
    <method>get</method>
    <method>post</method>
  </http>

  <commands>
    <command>read</command>
    <command>list</command>
  </commands>

</restrict>
```

But I still got: _java.lang.Exception: No access from client 127.0.0.1 allowed_

Same goes for other IPs. I tried adding my workstation IP explicitely, even the whole subnet:

```
  <remote>
    <host>127.0.0.1</host>
    <host>10.0.0.0/8</host>
    <host>10.208.40.186</host>
  </remote>
```

But whatever I do, still get the denied message and a 403.

Properties file:

```
# IP to bind to
host=0.0.0.0

# Port to listen to
port=7777

# Context path
#agentContext=/jolokia

# Basic authentication
user=<redacted>
password=<redacted>

# Use SSL
protocol=https

# Security ACL
policyLocation=/opt/jolokia/policy.xml
```

Using the JVM agent, jolokia-jvm-1.7.1.jar

**Comment by rhuss** [comment]
`policyLocation` is a URL, so you should use `file:///opt/jolokia/policy.xml` if you refer to a file on the local file system.

See also https://jolokia.org/reference/html/security.html#security-policy-location
