### ISSUE TITLE
Unable to use HashMap via ProxyMode

### ISSUE THREAD

**Issue by qtc-de** [rhuss/jolokia#542]
Hi there :wave: 

I have identified a bug when running Jolokia in *proxy mode* to forward requests to backend JMX endpoints. The documentation already mentions that *proxy mode* is limited, but I did not find a description for this bug yet. Solving this bug could be rather difficult, although I guess it should be possible.

The bug occurs when invoking a MBean method that expects a `Map` within it's arguments. The `Map` can be rather simple like `Map<String,String>` and therefore comply with the *OpenType* specification. The way *Jolokia* converts `Map` and `List` types into objects for forwarding them to *JMX* is pretty elegant. Here the corresponding Code from [StringToObjectConveter.java](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/converter/object/StringToObjectConverter.java):

```java
// trigger definition

        JSONParser jsonExtractor = new JSONParser();
        for (Class type : new Class[] { Map.class, List.class,
                                        JSONObject.class, JSONArray.class }) {
            PARSER_MAP.put(type.getName(),jsonExtractor);
        }

// and further below the parser definition

    private static class JSONParser implements Parser {

        /** {@inheritDoc} */
        public Object extract(String pValue) {
            try {
                return new org.json.simple.parser.JSONParser().parse(pValue);
            } catch (ParseException e) {
                throw new IllegalArgumentException("Cannot parse JSON " + pValue + ": " + e,e);
            }
        }
    }
```

With this implementation, all the heavy lifting is done by `JSONParser`, which is quite nice. The possible results should be either `JSONObject` or `JSONArray`, which extend the types `Map` and `List` and are therefore compatible. Therefore, an application with the *json-simple* library within the classpath will see no difference.

And here we are at the bugs root cause. What happens when the backend *JMX* service does not have *json-simple* within it's classpath? Well, it will raise a `ClassNotFoundException` meaning that all methods that are based on the types `Map` and `List` cannot be invoked when *json-simple* is not within the classpath.

Solving this issue seems easy, as one could simply convert `JSONObject` to `Map` and `JSONArray` to `List` by recursively applying `StringToObjectConveter` for each element. However, this would require to know the nested types, which is currently not possible as this information is not send during the client server communication. Moreover, possibly nested maps or lists make this even more difficult.

At the end, *MBean* methods that expect `Map` or `List` are probably not that common and the bug can be considered as an edge case. If you can fix it, great! If not, it is probably also fine. However, in this case one should think about adding another limitation to the documentation.

Best,
Tobias

**Comment by rhuss** [comment]
I updated the documentation in https://github.com/rhuss/jolokia/commit/c9dca4987141b80ef77b38e9f13d41d4b776f755 you might want to give it a quick review whether it is accurate. Thanks!
