### ISSUE TITLE
URL escaping rules are not sufficient with newer runtimes (like Jetty 11)

### ISSUE THREAD

**Issue by grgrzybek** [rhuss/jolokia#573]
Links:
* jakartaee/servlet#18
* eclipse/jetty.project#9444
* https://datatracker.ietf.org/doc/html/rfc2396
* https://datatracker.ietf.org/doc/html/rfc3986

For Jolokia 1.x with Jetty 6 (used in tests), I have proper:
```
$ curl -v -u jolokia:jolokia 'http://localhost:22333/j4p/read/jolokia.it:name=%5C!/,type=naming!//Ok'
...
> GET /j4p/read/jolokia.it:name=%5C!/,type=naming!//Ok HTTP/1.1
...
> 
< HTTP/1.1 200 OK
...
< Server: Jetty(6.1.26)
```

Because the only escaping done by `org.jolokia.client.request.J4pRequestHandler#escape()` is to replace `!` with `!!` and `/` with `!/` and `java.net.URI` changes `\` with `%5C`.

On Jolokia 2.0 with Jetty 11 I'm getting:
```
$ curl -v -u jolokia:jolokia 'http://localhost:22332/j4p/read/jolokia.it:name=%5C!/,type=naming!//Ok'
...
> GET /j4p/read/jolokia.it:name=%5C!/,type=naming!//Ok HTTP/1.1
...
> 
< HTTP/1.1 400 Bad Request
...
< Server: Jetty(11.0.6)
...
<h1>Bad Message 400</h1><pre>reason: Ambiguous empty segment in URI</pre>
```

**Comment by grgrzybek** [comment]
For the record - it's all about `org.eclipse.jetty.http.UriCompliance` and related `org.eclipse.jetty.http.UriCompliance.Violation`.

Most (except one related to UTF-16) violations refer to [RFC 3986, 3.3. Path](https://tools.ietf.org/html/rfc3986#section-3.3).

However JavaDoc for the `Violation` enum is a bit confusing:
> These are actual violations of the RFC, as they represent additional requirements in excess of the strict compliance of RFC 3986.

I'm not sure whether these violations are "actual" or "additional".

But here they are:
* AMBIGUOUS_PATH_SEGMENT - it's about `.` or `..` in paths (literal or URL encoded to `%2E` or `%u002E`)
* AMBIGUOUS_EMPTY_SEGMENT - it's about empty parts after splitting the path by `/` - **and that's the problem we see here**
* AMBIGUOUS_PATH_SEPARATOR - it's about encoded `/` within path segment (which is `%2F`)
* AMBIGUOUS_PATH_PARAMETER - it's about path parameters like `..;`
* AMBIGUOUS_PATH_ENCODING - it's about encoded `%` within path segment (which is `%25`)

Fortunately, `DEFAULT` Jetty 11 `org.eclipse.jetty.http.UriCompliance` allows _one_ violation: org.eclipse.jetty.http.UriCompliance.Violation#AMBIGUOUS_PATH_SEPARATOR, so we can simply encode `%2F`.

**Comment by rhuss** [comment]
Yes, I had a hard time with URL encoding in the past with various platforms, therefor this 'strange' escaping scheme. In general I'd recommend to use POST for complex naming, but still wanted to support GET schemes as much as possible. 🤞 that changing the escaping doesn't break other servers (I had some more sever issues with Tomcat to this regard, but this was really a long time ago)

**Comment by grgrzybek** [comment]
I bet no one in the world uses `name=with%3acolon` key value in `ObjectName` ;)
This is currently my problem - in Jolokia 1.x you simply encode `%3a` with `%253a`, but this is violation of `AMBIGUOUS_PATH_ENCODING` in Jetty.
This is the only test failure in `client/java` for now, but I'll think of something with least impact ;)

**Comment by tadayosi** [comment]
> I bet no one in the world uses `name=with%3acolon` key value in `ObjectName` ;)

I'd suspect Artemis broker might use such names. I saw some object names issues with Artemis before due to the unique naming of destinations in the broker.

**Comment by grgrzybek** [comment]
So I'll add documentation paragraph about the rules when using GET (and resulting from `org.eclipse.jetty.http.UriCompliance`). I'll check with Tomcat and Undertow too.

Mind that it's not a problem with POST.

**Comment by grgrzybek** [comment]
Even when changing from httpclient 4.5 (in Jolokia 1.x) to 4.5.14 (in Jolokia 2.0), we have differences.

For URI like `http://localhost:22332/j4p/read/jolokia.it:name=%5C!/,type=naming!//Ok`, double slash (`//`) is untouched by `org.apache.http.client.utils.URIUtils#rewriteURI()` in 4.5, but _normalized_ in 4.5.13.

See https://issues.apache.org/jira/browse/HTTPCLIENT-1968

**Comment by rhuss** [comment]
That's a pity because `/` is often part of an MBean name (when a path is used in an ObjectName as an attribute's value). In general we could think about removing that homegrown encoding scheme by something more invasive like an base64 encoding e.g. the ObjectName part (with some prefix indicating that encoding). This should be bulletproof. We could add this is in addition to the encoding right now for something like
`http://localhost:22332/j4p/read/b64:am9sb2tpYS5pdDpuYW1lPSU1Qwo=/Ok`

**Comment by grgrzybek** [comment]
I was thinking about base64 too, but in the end, I think it's more about documenting what's possible, what's nice and what's awkward when using path info.

in 6.1.1 chapter of reference doc you have:
> Instead of providing the information as path-info, a query parameter `p` can be used instead.

I want to add these rules, restrictions and new implications of [RFC 3986, section-3.3](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3) to the documentation.

**Comment by rhuss** [comment]
I see also some other options:

* Use a different HTTP client (okhttp)
* Disable the normalization feature of the HTTP client. Someone in that Apache there mentioned:

> To keep my application behavior (regarding uri normalization) same as 4.5.6, I need to set setNormalizeUri in RequestConfig to false in v4.5.8. This keeps the behavior same for special characters like "/", "+". Any other special characters that are still affected? Thanks.

**Comment by grgrzybek** [comment]
I disabled one violation on Jetty side (used for tests): https://github.com/jolokia/jolokia/blob/d8c95438/client/java/src/test/java/org/jolokia/client/request/AbstractJ4pIntegrationTest.java#L64-L66
And disabled _normalization_ on client side: https://github.com/jolokia/jolokia/blob/d8c95438/client/java/src/main/java/org/jolokia/client/J4pClientBuilder.java#L499

Ideally (that's my plan) I want to add some tests using different http clients (http 5, okio, ...)

**Comment by grgrzybek** [comment]
I've reviewed the escaping rules and added relevant documentation sections. Roughly:
* use POST in production
* if not, use `p` query parameter
* if not, use GET carefully

**Comment by grgrzybek** [comment]
I've reviewed the escaping rules and added relevant documentation sections. Roughly:
* use POST in production
* if not, use `p` query parameter
* if not, use GET carefully
