### ISSUE TITLE
connector to graphite / statsd etc

### ISSUE THREAD

**Issue by jstrachan** [rhuss/jolokia#62]
This one came up in the vertx community discussion around JMX and metrics etc
https://groups.google.com/forum/?fromgroups=#!topic/vertx/dqeE42_A-_Q

In the past I've used jmxtrans so that we can poll for jmx attributes and write them to one of a few different outputs (e.g. graphite / statsd). Most of these stat collectors take strings or JSON these days; so a connector is usually a pretty simple class. 

e.g. here's the jmxtrans code to write attributes to graphite
https://github.com/jmxtrans/jmxtrans/blob/master/src/com/googlecode/jmxtrans/model/output/GraphiteWriter.java#L105 

So given jolokia already has awesome URIs / JSON APIs to JMX and hides all the JMX crap :) - it would be pretty easy to configure in jolokia's XML config (or maybe via REST JSON calls on an mbean or something), to have a timer which polls a number of JMX attributes on a number of mbeans (using wildcards as jolokia already supports) then outputting them to an output source like graphite / statsd.

We could just reuse code from jmxtrans; but given how simple it is; just the odd class or two might do it. What some folks struggle with is figuring out which servers are running & where. So it might be nice if over jolokia HTTP/REST we could configure the servers at runtime. e.g. a JVM ships with sets of JMX attributes it would poll and report to graphite/statsd - then at runtime someone POSTs some JSON to define the running servers & then it starts firing requests. Or folks hard code it in the jolokia XML.

Given the proxying and REST/JSON of jolokia & its container agnostic easy integration with all JVMs; it could end up being a handy way to either push stats somewhere or to pull remote stats from remote JVMs (maybe which don't have jolokia inside them) and then write to graphite/statsd etc?

**Comment by rhuss** [comment]
Let's go for a similar functionality along with the health checks discussed in rhuss/jolokia-extra#1
