### ISSUE TITLE
Drop Java 1.5 support for Jolokia 2.x

### ISSUE THREAD

**Issue by rhuss** [rhuss/jolokia#72]
In order to keeps things as simple as possible (and because of the fact of limited resources), Java 1.5 support will be dropped for Jolokia 2.x. 

Java 1.5 users can still use the Jolokia 1.x series with the current feature set.

**Comment by apupier** [comment]
Java 1.5 has been already dropped

https://github.com/rhuss/jolokia/commit/3d259e4d65c9d8503f13b724fe91409b18496504

it was with Jolokia 1.5.0

**Comment by rhuss** [comment]
Thanks for the heads up @apupier !
